import { StyleSheet } from "react-native";
import { tokens } from "../../../theme/common.Style";

export const styles = StyleSheet.create({
    container: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 160, flexGrow: 1 },
    header: { position: "relative", height: 56, alignItems: "center", justifyContent: "center", paddingHorizontal: 20, marginTop: 20 },
    headerBackBtn: { position: "absolute", left: 0, top: 8 },
	headerCenter: { flex: 1 },
	headerRightSpace: { width: 40, height: 40 },
    headerTitle: { fontSize: 16, fontWeight: "700", lineHeight: 20, fontFamily: tokens.typography.fontFamily, color: "#000000" },
    top: { alignItems: "center", gap: 30 },
    profileImgWrap: { position: "relative", width: 120, height: 120, borderRadius: 999, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
    profileImg: { width: 102, height: 102, borderRadius: 999 },
    verifyBadge: { position: "absolute", right: 0, bottom: 0, width: 27, height: 27 },
    greeting: { fontSize: 24, fontWeight: "700", fontFamily: tokens.typography.fontFamily, color: "#000000" },
    name: { fontSize: 24, fontWeight: "700", fontFamily: tokens.typography.fontFamily, color: "#000000" },
    subText: { marginTop: -18, fontSize: 16, lineHeight: 20, fontWeight: "500", fontFamily: tokens.typography.fontFamily, color: "#A2A2A2" },
    cards: { alignItems: "center", flexDirection: "column" },
    verifyCard: { marginTop: 18, width: 160, height: 50, paddingHorizontal: 21, borderRadius: tokens.radius.r10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    verifyCardPending: { backgroundColor: "#F1F1F1" },
    verifyCardTitle: { fontSize: 16, fontWeight: "700", color: "#000000", fontFamily: tokens.typography.fontFamily },
    verifyCardTitlePending: { color: "#A2A2A2" },
    menu: { marginTop: 25, paddingHorizontal: 17, width: "100%", gap: 10 },
    menuItem: { width: "100%", height: 60, paddingHorizontal: 18, backgroundColor: "#FFFFFF", borderRadius: tokens.radius.r10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    menuTitle: { fontSize: 16, fontWeight: "600", fontFamily: tokens.typography.fontFamily, color: "#000000" },
    menuRight: { flexDirection: "row", alignItems: "center", gap: 5 },
    menuBotMargin: { height: 30, width: "100%", flexShrink: 0 },
    menuValue: { fontSize: 12, fontWeight: "600", fontFamily: tokens.typography.fontFamily, color: "#A2A2A2" },
    menuChevron: { width: 18, height: 18, transform: [{ rotate: "-90deg" }] },
    logoutDock: { position: "absolute", left: 0, right: 0, bottom: 0, paddingBottom: 53, alignItems: "center" },
    logoutBtn: { width: 200, height: 60, borderRadius: tokens.radius.r10, backgroundColor: tokens.colors.primary, alignItems: "center", justifyContent: "center" },
    logoutText: { fontSize: 16, fontWeight: "700", fontFamily: tokens.typography.fontFamily, color: "#FFFFFF" },
    withdrawBtn: { marginTop: 30, alignItems: "center", justifyContent: "center" },
    withdrawText: { fontSize: 16, fontWeight: "600", color: "#A2A2A2", textDecorationLine: "underline", fontFamily: tokens.typography.fontFamily },
    modalBackdrop: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: 46 },
    modalCard: { width: 300, height: 400, backgroundColor: "#FFFFFF", borderRadius: 20, paddingTop: 36, paddingHorizontal: 40, paddingBottom: 36, position: "relative", alignItems: "center" },
    modalClose: { position: "absolute", top: 8, right: 4, zIndex: 2 },
    modalBody: { flex: 1, width: "100%", marginTop: 53, marginBottom: 94, alignItems: "center", justifyContent: "flex-start" },
    modalTitle: { fontSize: 20, fontWeight: "700", color: "#000000", marginBottom: 66, textAlign: "center", fontFamily: tokens.typography.fontFamily },
    modalReason: { fontSize: 14, lineHeight: 20, fontWeight: "700", color: "#717171", textAlign: "center", fontFamily: tokens.typography.fontFamily },
    modalPrimaryButton: { height: 60, width: "100%", borderRadius: 10, backgroundColor: tokens.colors.primary, alignItems: "center", justifyContent: "center" },
    modalPrimaryButtonText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF", fontFamily: tokens.typography.fontFamily },
});