import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#F0F6FF", paddingHorizontal: 20, paddingTop: 20, paddingBottom: 32 },
    scrollContent: { paddingBottom: 220 },
    header: { height: 64, position: "relative", alignItems: "center", justifyContent: "center", paddingHorizontal: 20, paddingTop: 40 },
    backBtn: { position: "absolute", left: 2, top: 14 },
    hero: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 16, marginTop: 8 },
    copy: { flex: 1, marginLeft: 24 },
    title: { fontSize: 16, fontWeight: "700", lineHeight: 25, color: "#000000" },
    desc: { marginTop: 16, fontSize: 12, fontWeight: "400", lineHeight: 20, color: "#000000" },
    imageWrap: { width: 120, alignItems: "center", justifyContent: "center" },
    heroImage: { width: 120, height: 120 },
    card: { marginTop: 60, marginRight: 29, marginBottom: 0, marginLeft: 24, paddingTop: 21, paddingHorizontal: 14, paddingBottom: 24, backgroundColor: "#FFFFFF", borderRadius: 10, shadowColor: "#000000", shadowOpacity: 0.25, shadowRadius: 4, shadowOffset: { width: 0, height: 4 }, elevation: 4, overflow: "visible" },
    questionRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 37 },
    questionBadge: { width: 30, height: 30, borderRadius: 5, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    questionBadgeText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF" },
    question: { flex: 1, fontSize: 16, fontWeight: "700", lineHeight: 27, color: "#000000" },
    selectWrap: { position: "relative" },
    selectBtn: { width: "100%", minHeight: 36, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2E2E2", borderRadius: 10 },
    selectText: { flex: 1, fontSize: 16, fontWeight: "500", color: "#000000" },
    selectPlaceholder: { color: "#B4B4B4" },
    detailInput: { width: "100%", minHeight: 50, marginTop: 24, padding: 8, borderWidth: 1, borderColor: "#D9D9D9", borderRadius: 10, backgroundColor: "#FFFFFF", fontSize: 16, fontWeight: "500", lineHeight: 20, color: "#000000" },
    submitDock: { position: "absolute", left: 0, right: 0, bottom: 0, alignItems: "center", paddingBottom: 53 },
    submitBtn: { width: "90%", height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    submitBtnDisabled: { backgroundColor: "#F1F1F1" },
    submitBtnText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
    submitBtnTextDisabled: { color: "#A2A2A2" },
    bottomSpacer: { height: 300 },
    dropdownBackdrop: { flex: 1, backgroundColor: "rgba(0, 0, 0, 0.0)" },
    dropdownOverlay: { flex: 1, paddingHorizontal: 34, paddingTop: 350 },
    optionList: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9D9D9", borderRadius: 10, paddingBottom: 12, maxHeight: 280 },
    optionItem: { width: "100%", paddingVertical: 12, paddingHorizontal: 11 },
    optionText: { fontSize: 16, fontWeight: "400", color: "#000000" },
    optionTextSelected: { fontWeight: "700" },
});