import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    appTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "700", color: "#000000" },
    profileButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", overflow: "hidden" },
    profileImage: { width: 32, height: 32, borderRadius: 999, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9D9D9", },
    
    main: { flex: 1, paddingTop: 0, paddingHorizontal: 20, backgroundColor: "#F0F6FF" },
    scrollContent: { paddingBottom: 190 },
    titleSection: { marginBottom: 64 },
    
    activityTitle: { color: "#000000", fontSize: 24, fontWeight: "700", lineHeight: 28 },
    tabSection: { alignItems: "center", justifyContent: "center", marginBottom: 21 },
    tabText: { width: "40%", paddingBottom: 12, borderBottomWidth: 3, borderBottomColor: "#0166FF", color: "#0166FF", fontSize: 18, fontWeight: "700", lineHeight: 22, textAlign: "center" },
    rankingList: { gap: 10 },
    rankingCard: { width: "100%", minHeight: 64, paddingHorizontal: 15, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center" },
    rankBadge: { width: 24, height: 24, borderRadius: 12, alignItems: "center", justifyContent: "center", marginRight: 14 },
    rankBadgeTop: { backgroundColor: "#0166FF" },
    rankBadgeNormal: { backgroundColor: "#BDD8FF" },
    rankBadgeText: { fontSize: 14, fontWeight: "700", lineHeight: 16 },
    rankBadgeTextTop: { color: "#FFFFFF" },
    rankBadgeTextNormal: { color: "#0166FF" },
    
    studentName: { flex: 1, minWidth: 0, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 18 },
    scoreText: { minWidth: 64, color: "#000000", textAlign: "right", fontSize: 22, fontWeight: "700", lineHeight: 24 },
    trendWrap: { width: 56, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
    trendEmpty: { width: 56, height: 18 },
    trendTriangleUp: { width: 0, height: 0, borderLeftWidth: 6, borderRightWidth: 6, borderBottomWidth: 11, borderLeftColor: "transparent", borderRightColor: "transparent", borderBottomColor: "#FF1010" },
    trendTriangleDown: { width: 0, height: 0, borderLeftWidth: 6, borderRightWidth: 6, borderTopWidth: 11, borderLeftColor: "transparent", borderRightColor: "transparent", borderTopColor: "#0166FF" },
    trendTextUp: { color: "#FF1010", fontSize: 16, fontWeight: "700", lineHeight: 18 },
    trendTextDown: { color: "#0166FF", fontSize: 16, fontWeight: "700", lineHeight: 18 },
    
    myFloatingCard: { position: "absolute", left: 20, right: 20, bottom: 32, zIndex: 20, minHeight: 84, paddingLeft: 19, paddingRight: 16, borderRadius: 10, backgroundColor: "#0166FF", shadowColor: "#0166FF", shadowOpacity: 0.45, shadowRadius: 4, shadowOffset: { width: 0, height: 0 }, elevation: 6, flexDirection: "row", alignItems: "center" },
    myRankBadge: { width: 32, height: 32, borderRadius: 16, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
    myRankText: { color: "#0166FF", fontSize: 20, fontWeight: "700", lineHeight: 22 },
    myNameText: { flex: 1, minWidth: 0, paddingHorizontal: 17, color: "#FFFFFF", fontSize: 18, fontWeight: "700", lineHeight: 22 },
    myScoreText: { marginRight: 8, color: "#FFFFFF", fontSize: 24, fontWeight: "700", lineHeight: 28 },
    detailMain: { flex: 1, paddingHorizontal: 20, backgroundColor: "#F0F6FF" },
    detailScrollContent: { paddingBottom: 190 },
    detailInlineBackButton: { width: 44, height: 44, marginBottom: 11, alignItems: "flex-start", justifyContent: "center" },
    myPointCard: { minHeight: 160, paddingTop: 18, paddingHorizontal: 20, paddingBottom: 15, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", justifyContent: "flex-end" },
    myPointLabel: { color: "#000", fontSize: 20, fontWeight: "700", lineHeight: 24 },
    myPointValue: { color: "#000000", fontSize: 36, fontWeight: "700", lineHeight: 40, marginTop: 32, marginBottom: 7, },
    myPointRank: { color: "#6B6B6B", fontSize: 12, fontWeight: "700", lineHeight: 20 },
    
    logSection: { marginTop: 22 },
    logTitleRow: { minHeight: 44, marginLeft: 11, marginBottom: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    logSectionTitle: { color: "#000000", fontSize: 20, fontWeight: "700", lineHeight: 24 },
    filterButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
    logList: { gap: 10 },
    logCard: { width: "100%", minHeight: 84, paddingLeft: 20, paddingRight: 11, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 14, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 8 },
    logTextWrap: { flex: 1, minWidth: 0 },
    logTitle: { marginBottom: 5, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    logMeta: { color: "rgba(0, 0, 0, 0.50)", fontSize: 14, fontWeight: "500", lineHeight: 20 },
    logPoint: { minWidth: 80, height: 36, paddingHorizontal: 8, borderRadius: 18, alignItems: "center", justifyContent: "center" },
    logPointActive: { backgroundColor: "#BDD8FF" },
    logPointInactive: { backgroundColor: "#E7E7E7" },
    logPointText: { fontSize: 16, fontWeight: "700", lineHeight: 20 },
    logPointTextActive: { color: "#0166FF" },
    logPointTextInactive: { color: "#808080" },
    
    getPointButton: { position: "absolute", left: 20, right: 20, bottom: 32, zIndex: 20, height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    getPointButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700", lineHeight: 18 },
    state: { minHeight: 260, alignItems: "center", justifyContent: "center" },
    stateSmall: { minHeight: 120, alignItems: "center", justifyContent: "center" },
    emptyWrap: { minHeight: 120, alignItems: "center", justifyContent: "center" },
    emptyText: { color: "#808080", fontSize: 15, fontWeight: "700", lineHeight: 20, textAlign: "center" },
    modalBackdrop: { flex: 1, backgroundColor: "rgba(104, 104, 104, 0.50)", justifyContent: "flex-end" },
    
    filterSheet: { width: "100%", maxHeight: "55%", paddingTop: 15, paddingBottom: 34, borderTopLeftRadius: 10, borderTopRightRadius: 10, borderWidth: 1, borderColor: "#D9D9D9", backgroundColor: "#FFFFFF" },
    filterOption: { width: "100%", height: 55, paddingHorizontal: 33, justifyContent: "center", backgroundColor: "#FFFFFF" },
    filterOptionSelected: { backgroundColor: "#BDD8FF" },
    filterOptionText: { color: "#000000", fontSize: 20, fontWeight: "500", lineHeight: 24 },
    detailModalPage: { flex: 1, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 110, backgroundColor: "#F0F6FF" },
    detailBackButton: { width: 44, height: 44, marginBottom: 11, alignItems: "flex-start", justifyContent: "center" },
    
    logDetailCard: { width: "100%", paddingTop: 17, paddingHorizontal: 16, paddingBottom: 15, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF" },
    logDetailTop: { flexDirection: "row", alignItems: "center", gap: 13 },
    logDetailIcon: { width: 64, height: 64, borderRadius: 8, alignItems: "center", justifyContent: "center" },
    logDetailTextWrap: { flex: 1, minWidth: 0 },
    logDetailTitle: { marginBottom: 5, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    logDetailDate: { color: "rgba(0, 0, 0, 0.50)", fontSize: 14, fontWeight: "700", lineHeight: 20 },
    logDetailPoint: { minWidth: 64, height: 36, paddingHorizontal: 8, borderRadius: 18, alignItems: "center", justifyContent: "center" },
    logDetailPointText: { fontSize: 20, fontWeight: "700", lineHeight: 22 },
    logDetailStatus: { width: "100%", height: 48, marginTop: 16, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    logDetailStatusText: { fontSize: 16, fontWeight: "700", lineHeight: 18 },
    
    statusBgApproved: { backgroundColor: "#BDD8FF" },
    statusBgInactive: { backgroundColor: "#E7E7E7" },
    statusTextApproved: { color: "#0166FF" },
    statusTextInactive: { color: "#808080" },
    detailActionButton: { position: "absolute", left: 20, right: 20, bottom: 50, height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    detailActionButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700", lineHeight: 18 },
    
    missionPage: { flex: 1, backgroundColor: "#F0F6FF" },
    missionTopbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    missionHeaderIconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
    missionHeaderTitle: { flex: 1, textAlign: "center", color: "#000000", fontSize: 16, fontWeight: "700" },
    missionHeaderRightPlaceholder: { width: 44, height: 44 },
    missionMain: { flex: 1, paddingHorizontal: 13, backgroundColor: "#F0F6FF" },
    missionScrollContent: { paddingBottom: 80 },
    missionProgress: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginBottom: 32 },
    missionProgressBar: { flex: 1, height: 10, borderRadius: 5, backgroundColor: "#BDD8FF" },
    missionProgressBarActive: { backgroundColor: "#0166FF" },
    missionSelectHeader: { marginLeft: 18, marginRight: 8, marginBottom: 6, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    missionSelectTitle: { color: "#000000", fontSize: 24, fontWeight: "700", lineHeight: 28, letterSpacing: -0.4 },
    
    missionFilterTabs: { flexGrow: 1, paddingHorizontal: 7, paddingBottom: 20, flexDirection: "row", gap: 9 },
    missionFilterTab: { flex: 1, width: 112, height: 36, paddingHorizontal: 10, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 18, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
    missionFilterTabActive: { backgroundColor: "#BDD8FF", borderColor:"#BDD8FF", },
    missionFilterTabText: { color: "#808080", fontSize: 14, fontWeight: "500" },
    missionFilterTabTextActive: { color: "#0166FF" },
    missionList: { gap: 10, paddingHorizontal: 7, paddingBottom: 100,},
    missionCard: { minHeight: 84, paddingLeft: 20, paddingRight: 24, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center" },
    missionCardSelected: {  },
    missionCardDisabled: { opacity: 0.7 },
    missionRadio: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: "#E6E6E6", marginRight: 16 },
    missionRadioSelected: { borderColor: "#0166FF",  borderWidth: 6, backgroundColor: "#fff" },
    missionInfo: { flex: 1, minWidth: 0, marginRight: 9, },
    missionName: { marginBottom: 5, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    missionCategory: { color: "rgba(0, 0, 0, 0.50)", fontSize: 14, fontWeight: "500", lineHeight: 20 },
    missionPoint: { minWidth: 74, height: 36, paddingHorizontal: 10, borderRadius: 18, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    missionPointDisabled: { backgroundColor: "#E7E7E7" },
    missionPointText: { color: "#0166FF", fontSize: 16, fontWeight: "700" },
    missionPointTextDisabled: { color: "#808080" },
    
    missionNextButton: { position: "absolute", left: 20, right: 20, bottom: 32, zIndex: 20, height: 60, borderRadius: 10, backgroundColor: "#BDD8FF", color: "#0166FF", alignItems: "center", justifyContent: "center", },
    missionNextButtonDisabled: { backgroundColor: "#E7E7E7" },
    missionNextButtonDisabledText: { color: "#808080",},
    missionNextButtonText: { color: "#0166FF", fontSize: 16, fontWeight: "700" },
    missionUploadTitle: { marginLeft: 18, marginBottom: 18 },
    missionUploadTitleText: { color: "#000000", fontSize: 24, fontWeight: "700", lineHeight: 28 },
    missionSubmitSection: { gap: 16, paddingHorizontal: 7, paddingBottom: 180, },
    missionSubmitCard: { paddingTop: 20, paddingHorizontal: 20, paddingBottom: 8, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF" },
    missionSubmitCardTitle: { marginBottom: 24, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    missionInfoField: { marginBottom: 20 },
    missionInfoLabel: { marginBottom: 8, marginLeft: 7, color: "#000", fontSize: 14, fontWeight: "700" },
    missionReadonlyInput: { minHeight: 44, paddingHorizontal: 12, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 8, backgroundColor: "#fff", justifyContent: "center" },
    missionReadonlyInputText: { color: "#000000", fontSize: 15, fontWeight: "500" },
    missionFileLabel: { marginBottom: 8, marginHorizontal: 7, color: "#808080", fontSize: 14, fontWeight: "700" },
    missionUploadBox: { marginHorizontal: 7, minHeight: 100, borderWidth: 1, borderColor: "#E7E7E7", borderStyle: "dashed", borderRadius: 10, backgroundColor: "#fff", alignItems: "center", justifyContent: "center", gap: 0 },
    missionUploadGuide: { color: "#808080", fontSize: 14, fontWeight: "500", textAlign: "center", lineHeight: 24, },
    
    missionFileList: { marginTop: 12, gap: 8 },
    missionFileItem: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 16 },
    missionFileMain: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 16 },
    missionFileIcon: { width: 46, height: 24, alignItems: "center", justifyContent: "center", flexShrink: 0 },
    missionFileName: { flex: 1, minWidth: 0, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 24 },
    missionFileRemove: { width: 32, height: 32, alignItems: "center", justifyContent: "center", flexShrink: 0 },
    missionLinkArea: { marginTop: 6, marginHorizontal: 7, },
    missionLinkLabel: { marginBottom: 8, color: "#6B6B6B", fontSize: 14, fontWeight: "700" },
    missionLinkInput: { minHeight: 36, paddingHorizontal: 14, borderWidth: 1, borderColor: "#E7E7E7", borderRadius: 10, backgroundColor: "#FFFFFF", color: "#000000", fontSize: 12, fontWeight: "500", textAlignVertical: "center" },
    missionLinkInputInvalid: { borderColor: "#f00" },
    missionLinkError: { marginTop: 7, color: "#f00", fontSize: 12, fontWeight: "600" },
    missionSubmitButton: { marginBottom: 16, marginHorizontal: 7, marginTop: 20, height: 48, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    missionSubmitButtonDisabled: { backgroundColor: "#E7E7E7" },
    missionSubmitButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
    missionSubmitButtonDisabledText: { color: "#808080", },

    missionComplete: { minHeight: 520, alignItems: "center", justifyContent: "center", paddingHorizontal: 20 },
    missionCompleteIcon: { marginBottom: 11 },
    missionCompleteTitle: { color: "#0166FF", fontSize: 20, fontWeight: "700", lineHeight: 24, textAlign: "center" },
    missionCompleteFloatingBottom: { position: "absolute", left: 20, right: 20, bottom: 32, zIndex: 20 },
    missionCompleteNotice: { marginBottom: 20, color: "#808080", fontSize: 14, fontWeight: "500", lineHeight: 20, textAlign: "center" },
    missionCompleteButton: { height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    missionCompleteButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
});