import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#F0F6FF" },
    topbar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF", },
    iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center", },
    iconSpacer: { width: 44, height: 44, },
    appTitle: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4, },
    appTitleText: { fontSize: 16, fontWeight: "700", lineHeight: 22, color: "#000000", },
    appTitleStatus: { fontSize: 16,fontWeight: "700", lineHeight: 22, color: "#0166FF", },
    scrollContent: { flexGrow: 1, paddingTop: 11, paddingHorizontal: 12, paddingBottom: 200, },
    scrollContentPicker: { paddingBottom: 200, },
    grid: { width: "100%", flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" },
    photoTile: { position: "relative", width: "32.4%", aspectRatio: 1, marginBottom: 5, borderRadius: 8, backgroundColor: "#FFF", overflow: "hidden", alignItems: "center", justifyContent: "center" },
    cameraTile: { backgroundColor: "#E3E3E3" },
    galleryTile: { backgroundColor: "rgba(189, 216, 255, 0.5)" },
    selectedTile: { backgroundColor: "#DCEBFF" },
    photoImage: { width: "100%", height: "100%" },
    selectedIconWrap: { position: "absolute", right: 11, bottom: 11, width: 26, height: 26, alignItems: "center", justifyContent: "center" },
    galleryText: { fontSize: 20, fontWeight: "800", lineHeight: 24, color: "#0166FF" },
    noSelfieText: { marginTop: 40, fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#808080", textAlign: "center" },
    emptyWrap: { flex: 1, alignItems: "center", justifyContent: "center" },
    emptyText: { fontSize: 14, fontWeight: "700", lineHeight: 20, color: "#808080", textAlign: "center" },
    bottomBar: { position: "absolute", left: 0, right: 0, bottom: 0, zIndex: 20, paddingTop: 50, paddingHorizontal: 20, paddingBottom: 50, backgroundColor: "#F0F6FF",},
    primaryButton: { width: "100%", height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    primaryButtonDisabled: { backgroundColor: "#E3E3E3" },
    primaryButtonText: { fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#FFF" },
    primaryButtonTextDisabled: { color: "#808080" },
    
    cameraLayer: { flex: 1, backgroundColor: "#000" },
    cameraReviewImage: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
    cameraClose: { position: "absolute", top: 60, right: 12, zIndex: 2, width: 44, height: 44, alignItems: "center", justifyContent: "center" },
    cameraReviewActions: { position: "absolute", left: 20, right: 20, bottom: 50, zIndex: 4 },
    cameraReviewButton: { width: "100%", height: 60, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    cameraRetakeButton: { marginBottom: 32, backgroundColor: "#BDD8FF" },
    cameraCheckInButton: { backgroundColor: "#0166FF" },
    cameraRetakeText: { fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#0166FF", },
    cameraCheckInText: { fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#FFFFFF", },
    cameraRoot: { flex: 1, backgroundColor: "#000000", },
    cameraPreview: { ...StyleSheet.absoluteFillObject, }, 
    cameraGuide: { position: "absolute", left: 35, right: 35, zIndex: 3, minHeight: 64, borderWidth: 1, borderColor: "#FFFFFF", borderRadius: 12, backgroundColor: "rgba(255, 255, 255, 0.20)", alignItems: "center", justifyContent: "center", paddingHorizontal: 16, },
    cameraGuideText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700", lineHeight: 20, textAlign: "center", },
    cameraCapture: { position: "absolute", left: "50%", zIndex: 4, width: 106, height: 106, marginLeft: -53, borderWidth: 5, borderColor: "rgba(255, 255, 255, 0.5)", borderRadius: 999, backgroundColor: "#FFFFFF", },
    cameraSwitch: { position: "absolute", left: "50%", zIndex: 4, width: 48, height: 48, marginLeft: 98, borderRadius: 999, backgroundColor: "rgba(255, 255, 255, 0.35)", alignItems: "center", justifyContent: "center", },
        
    successLayer: { flex: 1, backgroundColor: "#F0F6FF", alignItems: "center", justifyContent: "center", gap: 6, },
    successText: { fontSize: 20, fontWeight: "700", lineHeight: 50, color: "#0166FF", },    
});