import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#F0F6FF" },
    topbar: { height: 56, paddingHorizontal: 20, backgroundColor: "#F0F6FF", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    iconButton: { width: 24, height: 24, alignItems: "center", justifyContent: "center" },
    menuIcon: { width: 24, height: 24, alignItems: "center", justifyContent: "center" },
    menuIconLine: { width: 18, height: 2, marginVertical: 2, borderRadius: 1, backgroundColor: "#000" },
    appTitle: { flex: 1, marginHorizontal: 12, fontSize: 17, fontWeight: "700", lineHeight: 22, color: "#000", textAlign: "center" },
    topbarSpacer: { width: 24, height: 24 },
    list: { flexGrow: 1, paddingTop: 14, paddingHorizontal: 20, paddingBottom: 40 },
    card: { width: "100%", minHeight: 80, marginBottom: 11, paddingLeft: 23, paddingRight: 17, borderWidth: 1, borderColor: "#E3E3E3", borderRadius: 10, backgroundColor: "#FFF", flexDirection: "row", alignItems: "center" },
    cardText: { flex: 1, minWidth: 0 },
    cardTitle: { marginBottom: 5, fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#000" },
    cardSubRow: { flexDirection: "row", alignItems: "center" },
    cardSubText: { marginRight: 4, fontSize: 14, fontWeight: "500", lineHeight: 20, color: "rgba(0, 0, 0, 0.50)" },
    cardTime: { fontSize: 14, fontWeight: "500", lineHeight: 20, color: "#848484" },
    statusBox: { minWidth: 84, height: 36, marginLeft: 6, paddingHorizontal: 10, borderRadius: 18, alignItems: "center", justifyContent: "center" },
    statusText: { fontWeight: "700", lineHeight: 18 },
    statusPresent: { backgroundColor: "#BDD8FF" },
    statusAbsent: { backgroundColor: "#F6DBDB" },
    statusLate: { backgroundColor: "#FFE7C7" },
    statusNotChecked: { backgroundColor: "#EAEAEA" },
    statusTextPresent: { fontSize: 16, color: "#0166FF" },
    statusTextAbsent: { fontSize: 16, color: "#F00" },
    statusTextLate: { fontSize: 12, color: "#FF8A00" },
    statusTextNotChecked: { fontSize: 12, color: "#777" },
    chevron: { width: 24, height: 24, marginLeft: 6, fontSize: 32, lineHeight: 24, color: "#848484", textAlign: "center" },
    emptyWrap: { marginTop: 80, alignItems: "center" },
    emptyText: { marginTop: 10, fontSize: 12, fontWeight: "700", lineHeight: 18, color: "#808080", textAlign: "center" },
});