import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#F0F6FF" },
    topbar: { height: 56, paddingHorizontal: 20, backgroundColor: "#F0F6FF", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    iconButton: { width: 24, height: 24, alignItems: "center", justifyContent: "center" },
    iconSpacer: { width: 24, height: 24 },
    appTitle: { flex: 1, marginHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "center" },
    appTitleText: { fontSize: 17, fontWeight: "700", lineHeight: 22, color: "#000" },
    appTitleStatus: { marginLeft: 4, fontSize: 17, fontWeight: "700", lineHeight: 22, color: "#0166FF" },
    scrollContent: { flexGrow: 1, paddingTop: 11, paddingHorizontal: 12, paddingBottom: 150 },
    scrollContentPicker: { paddingBottom: 200 },
    grid: { width: "100%", flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" },
    photoTile: { position: "relative", width: "32.4%", aspectRatio: 1, marginBottom: 5, borderRadius: 8, backgroundColor: "#FFF", overflow: "hidden", alignItems: "center", justifyContent: "center" },
    cameraTile: { backgroundColor: "#E3E3E3" },
    galleryTile: { backgroundColor: "rgba(189, 216, 255, 0.5)" },
    selectedTile: { backgroundColor: "#DCEBFF" },
    photoImage: { width: "100%", height: "100%" },
    selectedIconWrap: { position: "absolute", right: 11, bottom: 11, width: 26, height: 26, alignItems: "center", justifyContent: "center" },
    galleryText: { fontSize: 20, fontWeight: "800", lineHeight: 24, color: "#0166FF" },
    noSelfieText: { marginTop: 40, fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#808080", textAlign: "center" },
    emptyWrap: { flex: 1, alignItems: "center", justifyContent: "center" },
    emptyText: { fontSize: 14, fontWeight: "700", lineHeight: 20, color: "#808080", textAlign: "center" },
    bottomBar: { position: "absolute", left: 0, right: 0, bottom: 0, zIndex: 20, paddingTop: 50, paddingHorizontal: 20, paddingBottom: 50, backgroundColor: "#F0F6FF" },
    primaryButton: { width: "100%", height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    primaryButtonDisabled: { backgroundColor: "#E3E3E3" },
    primaryButtonText: { fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#FFF" },
    primaryButtonTextDisabled: { color: "#808080" },
    cameraLayer: { flex: 1, backgroundColor: "#000" },
    cameraReviewImage: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
    cameraClose: { position: "absolute", top: 60, right: 12, zIndex: 2, width: 44, height: 44, alignItems: "center", justifyContent: "center" },
    cameraReviewActions: { position: "absolute", left: 20, right: 20, bottom: 50, zIndex: 4 },
    cameraReviewButton: { width: "100%", height: 60, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    cameraRetakeButton: { marginBottom: 32, backgroundColor: "#BDD8FF" },
    cameraCheckInButton: { backgroundColor: "#0166FF" },
    cameraRetakeText: { fontSize: 20, fontWeight: "700", lineHeight: 24, color: "#0166FF" },
    cameraCheckInText: { fontSize: 20, fontWeight: "700", lineHeight: 24, color: "#FFF" },
    successLayer: { flex: 1, backgroundColor: "#F0F6FF", alignItems: "center", justifyContent: "center" },
    successText: { marginTop: 6, fontSize: 20, fontWeight: "700", lineHeight: 50, color: "#0166FF" },
});