import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop:11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    appTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "700", color: "#000000" },
    headerRightSpace: { width: 24, height: 24 },
    main: { flex: 1, paddingTop: 12, paddingRight: 20, paddingBottom: 30, paddingLeft: 20 },
    scrollContent: { paddingBottom: 80 },
    titleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginLeft: 4, marginBottom: 21 },
    title: { margin: 0, color: "#000000", fontSize: 20, fontWeight: "700", lineHeight: 36 },
    filterButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center", gap: 5 },
    list: { gap: 10 },
    card: { width: "100%", minHeight: 80, paddingTop: 17, paddingRight: 13, paddingBottom: 20, paddingLeft: 20, borderWidth: 1, borderColor: "#E3E3E3", borderRadius: 10, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center" },
    info: { flex: 1, minWidth: 0, gap: 5 },
    assignmentName: { color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    assignmentPeriod: { color: "#808080", fontSize: 12, fontWeight: "500", lineHeight: 20 },
    status: { width: 84, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", flexShrink: 0 },
    statusBefore: { backgroundColor: "#E8E8E8" },
    statusSubmitted: { backgroundColor: "#BDD8FF" },
    statusLateSubmitted: { backgroundColor: "#FFEEBF" },
    statusMissing: { backgroundColor: "#FFD6D2" },
    statusEvaluated: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E7E7E7", },
    statusTextEvaluated: { color: "#808080", },
    statusText: { fontSize: 14, fontWeight: "700" },
    statusTextBefore: { color: "#808080" },
    statusTextSubmitted: { color: "#0166FF" },
    statusTextLateSubmitted: { color: "#FABB05" },
    statusTextMissing: { color: "#FF0000" },
    arrowWrap: { width: 28, height: 28, alignItems: "center", justifyContent: "center", flexShrink: 0 },
    emptyWrap: { minHeight: 160, alignItems: "center", justifyContent: "center" },
    emptyText: { color: "#808080", fontSize: 15, fontWeight: "700", textAlign: "center" },
});