import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop:11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    appTitle: { fontSize: 16, fontWeight: "700", color: "#000", lineHeight: 20 },
    headerRightSpace: { width: 24, height: 24 }, 
    scroll: { flex: 1 },
    content: { paddingHorizontal: 20, paddingTop: 11, paddingBottom: 140 },

    titleRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 14 },
    titleTextWrap: { flex: 1, minWidth: 0 },
    subText: { marginBottom: 5, fontSize: 16, fontWeight: "700", color: "#808080", lineHeight: 20 },
    title: { fontSize: 24, fontWeight: "700", color: "#000", lineHeight: 44 },
    progressBadge: { minWidth: 64, height: 36, marginLeft: 16, paddingHorizontal: 8, borderRadius: 18, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    progressText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 20 },
    heroCard: { height: 240, marginBottom: 43, borderRadius: 10, backgroundColor: "#DCEAFF", alignItems: "center", justifyContent: "center", overflow: "hidden" },
    heroRecordButton: { height: 48, borderRadius: 10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    heroRecordText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 20 },
    heroThumbnailImage: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
    heroPlayButton: { width: 64, height: 64, borderRadius: 32, backgroundColor: "rgba(189, 216, 255, 0.85)", alignItems: "center", justifyContent: "center" },
    heroPlayTriangle: { width: 0, height: 0, marginLeft: 5, borderTopWidth: 14, borderBottomWidth: 14, borderLeftWidth: 20, borderTopColor: "transparent", borderBottomColor: "transparent", borderLeftColor: "#FFFFFF" },
    sectionTitle: { marginBottom: 17, fontSize: 20, fontWeight: "700", color: "#000", lineHeight: 24 },
    
    loadingWrap: { minHeight: 240, alignItems: "center", justifyContent: "center" },
    weekList: { gap: 10 },
    weekCard: { borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", overflow: "hidden" },
    weekCardOpen: { paddingBottom: 18 },
    weekHeader: { minHeight: 64, paddingLeft: 17, paddingRight: 24, flexDirection: "row", alignItems: "center" },
    checkCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: "#E6E6E6", alignItems: "center", justifyContent: "center", marginRight: 13 },
    checkCircleActive: { backgroundColor: "#BDD8FF" },
    weekTitleWrap: { flex: 1, minWidth: 0 },
    weekTitle: { fontSize: 16, fontWeight: "700", color: "#000", lineHeight: 20 },
    weekDate: { marginTop: 2, fontSize: 12, fontWeight: "500", color: "rgba(0, 0, 0, 0.50)", lineHeight: 20 },
    weekCount: { minWidth: 36, marginRight: 12, textAlign: "right", fontSize: 14, fontWeight: "700", color: "rgba(0, 0, 0, 0.50)", lineHeight: 20 },
    weekBody: { paddingHorizontal: 20, paddingTop: 4, },
    weekDesc: { marginBottom: 24, fontSize: 12, fontWeight: "500", color: "rgba(0, 0, 0, 0.50)", lineHeight: 20 },
    
    missionCard: { padding: 12, marginBottom: 16, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 12, backgroundColor: "#FFFFFF" },
    missionTopRow: { flexDirection: "row", alignItems: "center", marginBottom: 18 },
    missionThumb: { width: 64, height: 64, borderRadius: 8, backgroundColor: "#E6E6E6", alignItems: "center", justifyContent: "center", marginRight: 13, overflow: "hidden" },
    missionThumbDone: { backgroundColor: "#BDD8FF" },
    missionTitleWrap: { flex: 1, minWidth: 0, opacity: 0.69, },
    missionThumbImage: { width: "100%", height: "100%" },
    missionTitle: { fontSize: 16, fontWeight: "700", color: "#4F4F4F", lineHeight: 20 },
    missionDuration: { marginTop: 6, fontSize: 24, fontWeight: "700", color: "#000", lineHeight: 28 },
    missionInfoRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
    missionBadge: { minWidth: 48, height: 24, paddingHorizontal: 0, borderRadius: 18, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center", marginRight: 13 },
    missionBadgeText: { fontSize: 14, fontWeight: "700", color: "#0166FF", lineHeight: 16 },
    missionDesc: { flex: 1, fontSize: 14, fontWeight: "500", color: "rgba(0, 0, 0, 0.50)", lineHeight: 20 },
    missionRecordButton: { height: 48, marginTop: 21, borderRadius: 10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    missionRecordButtonActive: { backgroundColor: "#0166FF" },
    missionRecordText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 20 },
    missionRecordTextActive: { color: "#FFFFFF" },
    
    freeCaptureCard: { borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", overflow: "hidden", paddingBottom: 18 },

    captureOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "#444444", zIndex: 20 },
    captureThumbnail: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, width: "100%", height: "100%" },
    captureFallback: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "#444444" },
    captureCloseButton: { position: "absolute", top: 54, right: 28, width: 44, height: 44, alignItems: "center", justifyContent: "center" },
    captureCloseText: { fontSize: 52, fontWeight: "300", color: "#FFFFFF", lineHeight: 56 },
    captureCenter: { position: "absolute", top: "39%", left: 0, right: 0, alignItems: "center" },
    captureCheckCircle: { width: 128, height: 128, borderRadius: 64, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center", marginBottom: 52 },
    captureTitle: { fontSize: 32, fontWeight: "900", color: "#FFFFFF", lineHeight: 40 },
    captureBottom: { position: "absolute", left: 40, right: 40, bottom: 96, gap: 32 },
    captureAgainButton: { height: 122, borderRadius: 14, backgroundColor: "#D5E7FF", alignItems: "center", justifyContent: "center" },
    captureAgainText: { fontSize: 29, fontWeight: "900", color: "#0166FF", lineHeight: 36 },
    captureNextButton: { height: 122, borderRadius: 14, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    captureNextText: { fontSize: 29, fontWeight: "900", color: "#FFFFFF", lineHeight: 36 },
    
    bottomBar: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 28, backgroundColor: "#F4F8FF" },
    laterButton: { height: 88, borderRadius: 12, backgroundColor: "#F0F6FF", alignItems: "center", justifyContent: "center" },
    laterButtonText: { fontSize: 24, fontWeight: "700", color: "#000", lineHeight: 30 },
    editButton: { height: 88, borderRadius: 12, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    editButtonText: { fontSize: 24, fontWeight: "700", color: "#FFFFFF", lineHeight: 30 },

    modalBackdrop: { flex: 1, alignItems: "center", justifyContent: "center" },
    modalDim: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "rgba(0, 0, 0, 0.35)" },
    deleteModalBox: { width: "82%", paddingHorizontal: 22, paddingTop: 24, paddingBottom: 18, borderRadius: 16, backgroundColor: "#FFFFFF" },
    deleteModalTitle: { fontSize: 18, fontWeight: "800", color: "#000000", lineHeight: 24 },
    deleteModalDesc: { marginTop: 10, fontSize: 14, fontWeight: "500", color: "#808080", lineHeight: 20 },
    deleteModalButtonRow: { flexDirection: "row", gap: 10, marginTop: 24 },
    deleteCancelButton: { flex: 1, height: 48, borderRadius: 10, backgroundColor: "#E6E6E6", alignItems: "center", justifyContent: "center" },
    deleteCancelText: { fontSize: 15, fontWeight: "700", color: "#555555", lineHeight: 20 },
    deleteConfirmButton: { flex: 1, height: 48, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    deleteConfirmText: { fontSize: 15, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },

});