import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop:11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    appTitle: { fontSize: 16, fontWeight: "700", color: "#000", lineHeight: 20 },
    headerRightSpace: { width: 40, height: 40 }, 
    scroll: { flex: 1 },
    content: { paddingHorizontal: 16, paddingTop: 11, paddingBottom: 180 },

    titleRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 14, paddingHorizontal: 11, },
    titleTextWrap: { flex: 1, minWidth: 0 },
    subText: { marginBottom: 5, fontSize: 16, fontWeight: "700", color: "#808080", lineHeight: 20 },
    title: { fontSize: 24, fontWeight: "700", color: "#000", lineHeight: 44 },
    progressBadge: { minWidth: 64, height: 36, marginLeft: 16, paddingHorizontal: 8, borderRadius: 18, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    progressText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 20 },
    heroCard: { height: 240, marginBottom: 43, borderRadius: 10, backgroundColor: "#BDD8FF80", alignItems: "center", justifyContent: "center", overflow: "hidden" },
    heroThumbnailImage: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
    heroVideo: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
    heroTouchLayer: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 2 },
    videoControlBar: { position: "absolute", left: 15, right: 15, bottom: 12, zIndex: 4 },
    heroLoadingOverlay: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 6, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0, 0, 0, 0.25)" },
    heroRecordButton: { height: 48, borderRadius: 10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    heroRecordText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 20 },
    heroPlayerArea: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, alignItems: "center", justifyContent: "center" },
    heroEmptyText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 22 },
    videoProgressTrack: { height: 6, borderRadius: 6.5, backgroundColor: "rgba(255, 255, 255, 0.45)", overflow: "hidden" },
    videoProgressFill: { height: "100%", borderRadius: 2, backgroundColor: "#FFFFFF" },
    videoProgressHitArea: { height: 28, justifyContent: "center" },
    pauseIcon: { flexDirection: "row", alignItems: "center", justifyContent: "center" },
    pauseBar: { width: 6, height: 24, marginHorizontal: 3, borderRadius: 2, backgroundColor: "#FFFFFF" },
    playTriangle: { width: 0, height: 0, marginLeft: 5, zIndex: 4, borderTopWidth: 14, borderBottomWidth: 14, borderLeftWidth: 22, borderTopColor: "transparent", borderBottomColor: "transparent", borderLeftColor: "#FFFFFF" },
    playCircle: { position: "absolute", top: "50%", left: "50%", width: 64, height: 64, marginTop: -32, marginLeft: -32, borderRadius: 32, zIndex: 5, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    timeRow: { marginTop: 7, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    timeText: { fontSize: 12, fontWeight: "700", color: "#FFFFFF", lineHeight: 20, textShadowColor: "rgba(0, 0, 0, 0.25)", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 4 },
    sectionTitle: { marginBottom: 17, fontSize: 20, fontWeight: "700", color: "#000", lineHeight: 24, marginLeft: 11, },
    
    loadingWrap: { minHeight: 240, alignItems: "center", justifyContent: "center" },
    weekList: { gap: 10, paddingHorizontal: 4, },
    weekCard: { borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", overflow: "hidden" },
    weekCardOpen: { paddingBottom: 21 },
    weekHeader: { minHeight: 64, paddingLeft: 17, paddingRight: 24, flexDirection: "row", alignItems: "center" },
    checkCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: "#E6E6E6", alignItems: "center", justifyContent: "center", marginRight: 13 },
    checkCircleActive: { backgroundColor: "#BDD8FF" },
    weekTitleWrap: { flex: 1, minWidth: 0 },
    weekTitle: { fontSize: 16, fontWeight: "700", color: "#000", lineHeight: 20 },
    weekCount: { minWidth: 36, marginRight: 12, textAlign: "right", fontSize: 14, fontWeight: "700", color: "rgba(0, 0, 0, 0.50)", lineHeight: 20 },
    weekBody: { paddingHorizontal: 16, },
    weekDesc: { marginBottom: 10, fontSize: 12, fontWeight: "500", color: "rgba(0, 0, 0, 0.50)", lineHeight: 24 },
    
    missionCard: { padding: 12, marginBottom: 10, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 12, backgroundColor: "#FFFFFF" },
    missionTopRow: { flexDirection: "row", alignItems: "center", marginBottom: 17 },
    missionThumb: { width: 64, height: 64, borderRadius: 8, backgroundColor: "#E6E6E6", alignItems: "center", justifyContent: "center", marginLeft: 7, marginRight: 13, overflow: "hidden" },
    missionThumbDone: { backgroundColor: "#BDD8FF" },
    missionTitleWrap: { flex: 1, minWidth: 0, opacity: 0.69, },
    missionThumbImage: { width: "100%", height: "100%" },
    missionTitle: { fontSize: 16, fontWeight: "700", color: "#4F4F4F", lineHeight: 20 },
    missionDuration: { marginTop: 6, fontSize: 24, fontWeight: "700", color: "#000", lineHeight: 28 },
    missionInfoRow: { flexDirection: "row", alignItems: "center", marginBottom: 12, paddingLeft: 7, },
    missionBadge: { minWidth: 48, height: 24, paddingHorizontal: 0, borderRadius: 18, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center", marginRight: 13 },
    missionBadgeText: { fontSize: 14, fontWeight: "700", color: "#0166FF", lineHeight: 16 },
    missionDesc: { flex: 1, fontSize: 14, fontWeight: "500", color: "rgba(0, 0, 0, 0.50)", lineHeight: 20 },
    missionRecordButton: { height: 48, marginTop: 9, borderRadius: 10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    missionRecordButtonActive: { backgroundColor: "#0166FF" },
    missionRecordText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 20 },
    missionRecordTextActive: { color: "#FFFFFF" },
    
    freeCaptureCard: { borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", overflow: "hidden", paddingBottom: 18 },

    captureOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, zIndex: 20, justifyContent: "space-between" },
    captureOverlayLight: { backgroundColor: "#F4F8FF" },
    captureBody: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 20, paddingTop: 40, paddingBottom: 180 },
    captureActionArea: { position: "absolute", left: 20, right: 20, bottom: 50, gap: 10 },
    captureCloseButton: { position: "absolute", top: 14, right: 12, width: 44, height: 44, alignItems: "center", justifyContent: "center", zIndex: 5 },

    captureCheckIcon: { marginBottom: 14 },
    captureTitle: { fontSize: 20, fontWeight: "700", color: "#FFFFFF", lineHeight: 26, textAlign: "center" },

    captureAgainButton: { height: 60, borderRadius: 10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    captureAgainText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 24 },
    captureNextButton: { height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    captureNextText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF", lineHeight: 24 },

    captureSavingDotRow: { height: 28, flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: 12, marginBottom: 24 },
    captureSavingDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: "#BDD8FF" },
    captureSavingDotActive: { backgroundColor: "#0166FF" },
    captureSavingTitle: { fontSize: 24, fontWeight: "700", color: "#000000", lineHeight: 32, textAlign: "center" },

    captureSuccessImg: { width: 150, height: 150, marginBottom: 22 },
    captureSuccessTitle: { fontSize: 34, fontWeight: "700", color: "#000000", lineHeight: 44, textAlign: "center" },
    captureSuccessSubTitle: { marginTop: 18, fontSize: 20, fontWeight: "700", color: "#808080", lineHeight: 28, textAlign: "center" },

    captureBackgroundImage: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
    captureBackgroundFallback: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "#000000" },
    captureBackgroundDim: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "transparent" },

    captureBackgroundDimStrong: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "rgba(0, 0, 0, 0.35)" },
    captureSavingTitleWhite: { fontSize: 24, fontWeight: "700", color: "#FFFFFF", lineHeight: 32, textAlign: "center" },
    captureSuccessTitleWhite: { fontSize: 34, fontWeight: "700", color: "#FFFFFF", lineHeight: 44, textAlign: "center" },
    captureSuccessSubTitleWhite: { marginTop: 18, fontSize: 20, fontWeight: "700", color: "rgba(255, 255, 255, 0.72)", lineHeight: 28, textAlign: "center" },

    bottomGradientBar: { position: "absolute", left: 0, right: 0, bottom: 0, height: 160, paddingHorizontal: 20, paddingBottom: 28, justifyContent: "flex-end" },
    editButton: { height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    editButtonText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },

    menuModalBackdrop: { flex: 1, backgroundColor: "transparent" },
    menuBox: { position: "absolute", top: 76, right: 12, width: 160, height: 48, paddingLeft: 18, borderRadius: 10, backgroundColor: "#FFFFFF", justifyContent: "center", shadowColor: "#000000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 12, elevation: 8 },
    menuDeleteText: { fontSize: 16, fontWeight: "700", color: "#808080", lineHeight: 20 },

    modalBackdrop: { flex: 1, position: "relative", alignItems: "center", justifyContent: "center" },
    modalBlur: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
    modalDim: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "rgba(0, 0, 0, 0.35)" },
    deleteModalBox: { width: "76%", height: 240, paddingHorizontal: 25, paddingTop: 87, paddingBottom: 17, borderRadius: 20, backgroundColor: "#FFFFFF" },
    deleteModalTitle: { fontSize: 16, fontWeight: "700", color: "#000000", lineHeight: 24, textAlign: "center", },
    deleteModalButtonRow: { flexDirection: "row", gap: 9, marginTop: "auto" },
    deleteCancelButton: { flex: 1, height: 48, borderRadius: 8, backgroundColor: "#FFC4C4", alignItems: "center", justifyContent: "center" },
    deleteCancelText: { fontSize: 16, fontWeight: "700", color: "#FF3838", lineHeight: 20 },
    deleteConfirmButton: { flex: 1, height: 48, borderRadius: 8, backgroundColor: "#FF3838", alignItems: "center", justifyContent: "center" },
    deleteConfirmText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },
    
    deleteCompleteModalBox: { width: "76%", height: 240, paddingHorizontal: 30, paddingTop: 87, paddingBottom: 17, borderRadius: 20, backgroundColor: "#FFFFFF" },
    deleteCompleteModalTitle: { fontSize: 16, fontWeight: "700", color: "#000000", lineHeight: 24, textAlign: "center" },
    deleteCompleteButton: { height: 48, marginTop: "auto", borderRadius: 8, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    deleteCompleteButtonText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },

    cameraRoot: { flex: 1, backgroundColor: "transparent" },
    cameraPreview: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
    cameraOverlay: { flex: 1, backgroundColor: "transparent" },

    cameraCloseButtonWrap: { position: "absolute", zIndex: 20 },
    cameraCloseIconBox: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },

    cameraMissionCard: { position: "absolute", borderWidth: 1, borderColor: "#FFFFFF", borderRadius: 12, backgroundColor: "rgba(255, 255, 255, 0.20)", alignItems: "flex-start" },
    cameraMissionCardPortrait: { padding: 18, },
    cameraMissionCardLandscape: { padding: 18,},
    cameraMissionTitle: { fontSize: 14, fontWeight: "700", color: "#fff", lineHeight: 20, textAlign: "left", opacity: 0.69, },
    cameraMissionDuration: { marginTop: 4, fontSize: 24, fontWeight: "700", color: "#FFFFFF", lineHeight: 28, textAlign: "left" },
    cameraMissionInfoScroll: { marginTop: 12, width: "100%", },
    cameraMissionInfoWrap: { gap: 10, },
    cameraMissionInfoRow: { flexDirection: "row", alignItems: "center" },
    cameraMissionBadge: { minWidth: 48, height: 24, paddingHorizontal: 8, borderRadius: 18, backgroundColor: "rgba(255, 255, 255, 0.20)", alignItems: "center", justifyContent: "center", marginRight: 16 },
    cameraMissionBadgeText: { fontSize: 14, fontWeight: "700", color: "#fff", lineHeight: 24 },
    cameraMissionDesc: { flex: 1, fontSize: 14, fontWeight: "500", color: "rgba(255, 255, 255, 0.50)", lineHeight: 20 },

    cameraFoldButtonInner: { flex: 1, width: "100%", height: "100%", alignItems: "center", justifyContent: "center" },
    cameraFoldButton: { position: "absolute", width: 32, height: 32, borderRadius: 16, backgroundColor: "rgba(255, 255, 255, 0.24)", alignItems: "center", justifyContent: "center", zIndex: 20 },

    cameraRecordArea: { position: "absolute", alignItems: "center", justifyContent: "center" },
    cameraRecordAreaPortrait: { left: 0, right: 0, bottom: 60 },
    cameraRecordAreaLandscape: { right: 60, top: "50%", marginTop: -53 },

    recordCircleOuter: { width: 106, height: 106, borderRadius: 53, borderWidth: 5, borderColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
    recordCircleInner: { width: 96, height: 96, borderRadius: 48, backgroundColor: "#FF3838" },
    recordStopInner: { width: 54, height: 54, borderRadius: 5, backgroundColor: "#FF3838" },
    cameraRecordTime: { marginTop: 12, fontSize: 16, fontWeight: "800", color: "#FFFFFF", lineHeight: 20 },

});