import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop:11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    iconButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
    appTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "700", color: "#000000" },
    main: { flex: 1, paddingTop: 27, paddingRight: 20, paddingLeft: 20, paddingBottom: 30, margin: 0, },

    topActions: { flexDirection: "row", alignItems: "center", gap: 6, }, 
    dashboardIconButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center", },
    profileButton: { width: 44, height: 44, borderRadius: 999, alignItems: "center", justifyContent: "center", overflow: "hidden", },
    profileImage: { width: 32, height: 32, borderRadius: 999, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9D9D9", },

    scrollContent: { paddingBottom: 80 },
    titleSection: { marginBottom: 24, paddingHorizontal: 4 },
    todayText: { marginLeft: 3, color: "#808080", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    activityTitle: { marginTop: 11, color: "#000000", fontSize: 24, fontWeight: "700", lineHeight: 28 },
    progressCard: { minHeight: 160, paddingTop: 18, paddingRight: 16, paddingBottom: 22, paddingLeft: 16, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", justifyContent: "space-between", marginBottom: 10 },
    progressLabel: { marginLeft: 4, color: "#6B6B6B", fontSize: 14, fontWeight: "700" },
    progressValue: { marginLeft: 7, color: "#000000", fontSize: 36, fontWeight: "700", lineHeight: 40 },
    progressTrack: { width: "100%", height: 8, borderRadius: 7, backgroundColor: "#BDD8FF", overflow: "hidden" },
    progressFill: { height: "100%", borderRadius: 7, backgroundColor: "#0166FF" },
    metricCard: { width: "100%", minHeight: 84, marginBottom: 10, paddingTop: 15, paddingRight: 12, paddingBottom: 20, paddingLeft: 12, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center" },
    metricTextWrap: { flex: 1, minWidth: 0, marginLeft: 8, gap: 7 },
    metricLabel: { color: "#6B6B6B", fontSize: 14, fontWeight: "700", lineHeight: 20 },
    metricValue: { color: "#000000", fontSize: 24, fontWeight: "700", lineHeight: 28 },
    metricBadge: { minWidth: 84, height: 36, paddingHorizontal: 10, borderRadius: 18, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    metricBadgePrimary: { backgroundColor: "#0166FF" },
    metricBadgeText: { color: "#0166FF", fontSize: 16, fontWeight: "700" },
    metricBadgeTextPrimary: { color: "#FFFFFF" },
    metricArrow: { width: 36, height: 36, marginLeft: 2, alignItems: "center", justifyContent: "center" },
    
    scheduleSection: { marginTop: 18, },
    scheduleHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginLeft: 11, marginRight: 1, marginBottom: 21, },
    scheduleTitle: { color: "#000000", fontSize: 20, fontWeight: "700", lineHeight: 24, },
    scheduleActions: { flexDirection: "row", alignItems: "center", gap: 10, },
    scheduleActionButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center", },
    scheduleList: { gap: 10 },
    scheduleItem: { width: "100%", minHeight: 84, paddingVertical: 18, paddingHorizontal: 20, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 14, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 14 },
    scheduleIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: "#E7E7E7", alignItems: "center", justifyContent: "center" },
    scheduleIconCompleted: { backgroundColor: "#BDD8FF" },
    scheduleTextWrap: { flex: 1, minWidth: 0, gap: 5 },
    scheduleItemTitle: { color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    scheduleItemDate: { color: "rgba(0, 0, 0, 0.50)", fontSize: 14, fontWeight: "500", lineHeight: 20 },

    filterModalBackdrop: { flex: 1, backgroundColor: "rgba(104, 104, 104, 0.50)", justifyContent: "flex-end",},
    filterModal: { width: "100%", minHeight: 162, paddingTop: 15, paddingBottom: 34, borderTopLeftRadius: 10, borderTopRightRadius: 10, borderWidth: 1, borderColor: "#D9D9D9", backgroundColor: "#FFFFFF", overflow: "hidden", },
    filterModalOption: { width: "100%", height: 55, paddingHorizontal: 33, justifyContent: "center", backgroundColor: "#FFFFFF", },
    filterModalOptionSelected: { backgroundColor: "#BDD8FF", },
    filterModalOptionText: { color: "#000000", fontSize: 20, fontWeight: "500", lineHeight: 55, },

    empty: { minHeight: 120, color: "#808080", fontSize: 15, fontWeight: "700", textAlign: "center", textAlignVertical: "center" },
    emptyWrap: { minHeight: 120, alignItems: "center", justifyContent: "center" },
});