import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop:11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    iconButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
    appTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "700", color: "#000000" },
    headerRightSpace: { width: 36, height: 36 },
    main: { flex: 1, paddingTop: 13, paddingRight: 20, paddingBottom: 40, paddingLeft: 20 },
    scrollContent: { paddingBottom: 80 },
    titleRow: { flexDirection: "row", alignItems: "center", gap: 3, marginBottom: 10 },
    backButton: { width: 30, height: 36, alignItems: "center", justifyContent: "center" },
    title: { flex: 1, color: "#000000", fontSize: 20, fontWeight: "700", lineHeight: 36 },
    card: { width: "100%", marginBottom: 16, paddingTop: 20, paddingRight: 17, paddingBottom: 24, paddingLeft: 20, borderWidth: 1, borderColor: "#E3E3E3", borderRadius: 14, backgroundColor: "#FFFFFF" },
    cardTitle: { marginBottom: 24, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    field: { marginBottom: 20 },
    fieldLabel: { marginBottom: 8, marginLeft: 7, color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 18 },
    readonlyInput: { width: "100%", height: 48, paddingHorizontal: 9, borderWidth: 1, borderColor: "#DDDDDD", borderRadius: 4, backgroundColor: "#FFFFFF", justifyContent: "center" },
    readonlyInputText: { color: "#000000", fontSize: 14, fontWeight: "500" },
    period: { marginBottom: 20 },
    periodRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    periodInput: { flex: 1, height: 48, paddingHorizontal: 9, borderWidth: 1, borderColor: "#DDDDDD", borderRadius: 4, backgroundColor: "#FFFFFF", justifyContent: "center" },
    periodDash: { width: 20, color: "#808080", fontSize: 20, fontWeight: "500", textAlign: "center" },
    grid: { flexDirection: "row", gap: 28 },
    gridItem: { flex: 1 },
    uploadBox: { marginTop: -8, width: "100%", height: 100, borderWidth: 1, borderStyle: "dashed", borderColor: "#E7E7E7", borderRadius: 4, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", gap: 4 },
    uploadText: { color: "#808080", fontSize: 12, fontWeight: "500", lineHeight: 24 },
    linkArea: { marginTop: 16 },
    linkAreaOnly: { marginTop: -8 },
    linkInput: { width: "100%", height: 36, paddingHorizontal: 20, borderWidth: 1, borderColor: "#E7E7E7", borderRadius: 8, backgroundColor: "#FFFFFF", color: "#000000", fontSize: 12, fontWeight: "500" },
    linkInputInvalid: { borderColor: "#FF0000" },
    linkError: { marginTop: 8, color: "#FF0000", fontSize: 12, fontWeight: "700" },
    linkItem: { minHeight: 36, marginTop: 12, paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: "#EEEEEE", borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 8 },
    linkText: { flex: 1, minWidth: 0, color: "#0166FF", fontSize: 12, fontWeight: "700" },
    linkRemoveButton: { width: 28, height: 28, alignItems: "center", justifyContent: "center" },
    submittedBar: { height: 40, marginTop: 16, paddingHorizontal: 9, borderWidth: 1, borderColor: "#E7E7E7", borderRadius: 4, backgroundColor: "#F1F1F1", flexDirection: "row", alignItems: "center", gap: 8 },
    submittedBarTitle: { color: "rgba(0, 0, 0, 0.72)", fontSize: 14, fontWeight: "500" },
    submittedBarLabel: { marginLeft: "auto", color: "#000000", fontSize: 12, fontWeight: "500" },
    submittedBarDate: { color: "#000000", fontSize: 12, fontWeight: "500" },
    fileList: { marginTop: 16, gap: 4 },
    fileItem: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 16 },
    fileMain: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 16 },
    fileIcon: { width: 46, height: 24, alignItems: "center", justifyContent: "flex-end" },
    fileNameWrap: { flex: 1, minWidth: 0, gap: 4 },
    fileName: { color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 24 },
    fileWarning: { color: "#FF0000", fontSize: 12, fontWeight: "500", lineHeight: 15 },
    fileActions: { flexDirection: "row", alignItems: "center", gap: 8 },
    fileActionButton: { width: 28, height: 28, borderRadius: 8, alignItems: "center", justifyContent: "center" },
    fileRemoveButton: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
    buttonRow: { alignItems: "flex-end", paddingBottom: 20 },
    submitButton: { width: 120, height: 48, borderRadius: 8, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    submitButtonDisabled: { backgroundColor: "#F1F1F1" },
    submitButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
    submitButtonTextDisabled: { color: "#A2A2A2" },
    emptyWrap: { minHeight: 240, alignItems: "center", justifyContent: "center" },
    emptyText: { color: "#808080", fontSize: 15, fontWeight: "700", textAlign: "center" },
    modalBackdrop: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 3000, backgroundColor: "rgba(209, 209, 209, 0.50)", alignItems: "center", justifyContent: "center", paddingHorizontal: 46 },
    modal: { width: "100%", maxWidth: 300, minHeight: 304, paddingTop: 55, paddingRight: 70, paddingBottom: 45, paddingLeft: 70, borderRadius: 20, backgroundColor: "#FFFFFF", shadowColor: "#000000", shadowOpacity: 0.25, shadowRadius: 10, elevation: 8, alignItems: "center" },
    modifymodal: { width: "100%", maxWidth: 300, minHeight: 304, paddingTop: 55, paddingHorizontal: 25, paddingBottom: 45, borderRadius: 20, backgroundColor: "#FFFFFF", shadowColor: "#000000", shadowOpacity: 0.25, shadowRadius: 10, elevation: 8, alignItems: "center" },
    modalIcon: { width: 80, height: 80, alignItems: "center", justifyContent: "center", marginBottom: 16 },
    modalTitle: { color: "#000000", fontSize: 20, fontWeight: "400", lineHeight: 27, marginBottom: 31, textAlign: "center", },
    modalButton: { width: 120, height: 48, borderRadius: 8, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    modalButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
    modalMessage: { marginTop: 8, marginBottom: 24, color: "#808080", fontSize: 16, fontWeight: "700", lineHeight: 22, textAlign: "center" },
    modalButtonRow: { width: "100%", flexDirection: "row", gap: 10 },
    modalSecondaryButton: { backgroundColor: "#E6E6E6" },
    modalSecondaryButtonText: { color: "#808080" },
});