import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop:11, paddingHorizontal: 12, paddingBottom: 15, backgroundColor: "#F0F6FF" },
    scroll: { flex: 1, backgroundColor: "#F0F6FF" },
    content: { paddingHorizontal: 16, paddingTop: 11, paddingBottom: 300 },
    titleWrap: { marginBottom: 23, paddingHorizontal: 11, },
    subText: { marginBottom: 9, fontSize: 16, fontWeight: "700", color: "#808080", lineHeight: 20 },
    title: { fontSize: 24, fontWeight: "700", color: "#000", lineHeight: 28 },
    loadingWrap: { minHeight: 180, alignItems: "center", justifyContent: "center" },

    previewCard: { height: 240, marginBottom: 21, borderRadius: 12, backgroundColor: "#BDD8FF80", overflow: "hidden" },
    previewPressLayer: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 2 },
    previewProgressTouchArea: { position: "absolute", top: 0, left: 16, right: 16, height: 48, zIndex: 30, elevation: 30, justifyContent: "center" },
    previewProgressRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    previewLoadingOverlay: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 20, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0, 0, 0, 0.12)" },
    previewCenter: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, alignItems: "center", justifyContent: "center", paddingTop: 22 },
    previewPlayOnlyCenter: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, alignItems: "center", justifyContent: "center" },
    previewWeek: { marginTop: 4, fontSize: 16, fontWeight: "700", color: "#FFF", lineHeight: 20 },
    previewTitle: { marginTop: 0, fontSize: 16, fontWeight: "700", color: "#FFF", lineHeight: 20 },
    previewTimeRow: { position: "absolute", left: 15, right: 15, bottom: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    previewTime: { fontSize: 12, fontWeight: "700", color: "#FFFFFF", lineHeight: 20, textShadowColor: "rgba(0, 0, 0, 0.25)", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 4 },
    previewVideo: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
    previewProgressTrack: { flex: 1, height: 6, borderRadius: 6, backgroundColor: "rgba(255, 255, 255, 0.50)", overflow: "hidden" },
    previewProgressFill: { height: "100%", borderRadius: 6, backgroundColor: "#FFFFFF" },
    playIconShadow: { width: 72, height: 72, borderRadius: 36, shadowColor: "#000000", shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.25, shadowRadius: 4, elevation: 4 },
    previewThumbnailImage: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },

    clipCard: { height: 64, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", paddingLeft: 7, paddingRight: 4, marginBottom: 12, marginHorizontal: 4,  },
    clipThumb: { width: 48, height: 48, borderRadius: 4, backgroundColor: "#BDD8FF", marginRight: 11 },
    clipTextWrap: { flex: 1, minWidth: 0 },
    clipTitle: { fontSize: 16, fontWeight: "700", color: "#000", lineHeight: 20 },
    clipWeek: { marginTop: 2, fontSize: 12, fontWeight: "500", color: "#00000080", lineHeight: 20 },
    clipDuration: { width: 36, textAlign: "center", fontSize: 14, fontWeight: "700", color: "#00000080", lineHeight: 20 },
    clipCardDragging: { shadowColor: "#000", shadowOpacity: 0.25, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 8, transform: [{ scale: 1.02 }] },
    clipThumbImage: { width: "100%", height: "100%", borderRadius: 4, },
    clipTitleInput: { height: 20, paddingVertical: 0, paddingHorizontal: 0, fontSize: 16, fontWeight: "700", color: "#000", lineHeight: 20, backgroundColor: "transparent" },

    titleEditModalBox: { width: "84%", paddingHorizontal: 22, paddingTop: 24, paddingBottom: 18, borderRadius: 16, backgroundColor: "#FFFFFF" },
    titleEditModalTitle: { fontSize: 18, fontWeight: "800", color: "#000", lineHeight: 24 },
    titleEditInput: { height: 52, marginTop: 18, paddingHorizontal: 14, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", fontSize: 17, fontWeight: "700", color: "#000" },
    titleEditButtonRow: { flexDirection: "row", gap: 10, marginTop: 18 },
    titleEditCancelButton: { flex: 1, height: 48, borderRadius: 10, backgroundColor: "#E6E6E6", alignItems: "center", justifyContent: "center" },
    titleEditCancelText: { fontSize: 15, fontWeight: "700", color: "#555555", lineHeight: 20 },
    titleEditConfirmButton: { flex: 1, height: 48, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    titleEditConfirmText: { fontSize: 15, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },

    deleteActionButton: { width: 64, height: 64, marginBottom: 12, borderRadius: 10, backgroundColor: "#FF3838", alignItems: "center", justifyContent: "center" },
    deleteActionText: { fontSize: 14, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },

    emptyText: { fontSize: 16, fontWeight: "700", color: "#808080", lineHeight: 22 },

    dragHandle: { width: 44, height: 44, alignItems: "center", justifyContent: "center", marginLeft: 3 },
    addClipButton: { height: 60, borderRadius: 10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center", marginTop: 6, marginHorizontal: 4, },
    addClipText: { fontSize: 16, fontWeight: "700", color: "#0166FF", lineHeight: 20 },
    bottomGradientBar: { position: "absolute", left: 0, right: 0, bottom: 0, height: 160, paddingHorizontal: 20, paddingBottom: 50, justifyContent: "flex-end" },
    exportButton: { height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    exportButtonDisabled: { opacity: 0.6 },
    exportButtonText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },

    modalBackdrop: { flex: 1, alignItems: "center", justifyContent: "center" },
    modalDim: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "rgba(0, 0, 0, 0.35)" },

    exportOverlay: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 50, backgroundColor: "#F0F6FF" },
    exportLoadingCenter: { flex: 1, alignItems: "center", justifyContent: "center" },
    exportDotRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: 12, height: 40, marginBottom: 17 },
    exportDot: { width: 12, height: 12, borderRadius: 6 },
    exportLoadingText: { fontSize: 24, fontWeight: "700", color: "#000000", lineHeight: 36, textAlign: "center" },

    exportDoneCenter: { flex: 1, alignItems: "center", justifyContent: "center" },
    exportMascot: { width: 160, height: 160, marginBottom: 18 },
    exportDoneTitle: { fontSize: 24, fontWeight: "700", color: "#000", lineHeight: 32, textAlign: "center" },
    exportDoneSubText: { marginTop: 18, fontSize: 16, fontWeight: "700", color: "#808080", lineHeight: 20, textAlign: "center" },
    exportDoneBottomBar: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 50, backgroundColor: "#F0F6FF" },
    exportDoneButton: { height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    exportDoneButtonText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF", lineHeight: 20 },

    addClipModalBackdrop: { flex: 1, paddingHorizontal: 20, backgroundColor: "rgba(0, 0, 0, 0.35)", alignItems: "center", justifyContent: "center" },
    addClipModalBox: { width: "100%", maxHeight: "82%", borderRadius: 18, backgroundColor: "#FFFFFF", paddingHorizontal: 18, paddingTop: 22, paddingBottom: 18 },
    addClipModalTitle: { fontSize: 20, fontWeight: "800", color: "#000000", lineHeight: 26, marginBottom: 16 },
    addClipModalButton: { height: 52, borderRadius: 10, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center", marginBottom: 10 },
    addClipModalButtonText: { fontSize: 15, fontWeight: "800", color: "#0166FF", lineHeight: 20 },
    addClipModalCancelButton: { height: 48, borderRadius: 10, backgroundColor: "#F2F2F2", alignItems: "center", justifyContent: "center", marginTop: 14 },
    addClipModalCancelText: { fontSize: 15, fontWeight: "700", color: "#555555", lineHeight: 20 },
    excludedClipSection: { marginTop: 10 },
    excludedClipTitle: { fontSize: 15, fontWeight: "800", color: "#000000", lineHeight: 20, marginBottom: 10 },
    excludedClipEmptyText: { fontSize: 14, fontWeight: "600", color: "#808080", lineHeight: 20, paddingVertical: 14 },
    excludedClipList: { maxHeight: 240 },
    excludedClipItem: { height: 64, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", paddingHorizontal: 8, marginBottom: 8 },
    excludedClipThumb: { width: 46, height: 46, borderRadius: 5, backgroundColor: "#BDD8FF", marginRight: 10, overflow: "hidden" },
    excludedClipThumbImage: { width: "100%", height: "100%" },
    excludedClipTextWrap: { flex: 1, minWidth: 0 },
    excludedClipName: { fontSize: 15, fontWeight: "800", color: "#000000", lineHeight: 20 },
    excludedClipMeta: { marginTop: 2, fontSize: 12, fontWeight: "600", color: "#808080", lineHeight: 18 },
    excludedClipAddText: { width: 48, textAlign: "right", fontSize: 14, fontWeight: "800", color: "#0166FF", lineHeight: 20 },
});