import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scroll: { flex: 1, backgroundColor: "#F4F8FF" },
    content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 150 },
    backButton: { width: 44, height: 44, alignItems: "flex-start", justifyContent: "center", marginBottom: 34 },
    titleWrap: { marginBottom: 22 },
    subText: { marginBottom: 8, fontSize: 28, fontWeight: "800", color: "#7E7E7E", lineHeight: 36 },
    title: { fontSize: 42, fontWeight: "900", color: "#05070A", lineHeight: 52 },
    loadingWrap: { minHeight: 180, alignItems: "center", justifyContent: "center" },

    previewCard: { height: 478, marginBottom: 28, borderRadius: 18, backgroundColor: "#D5E7FF", overflow: "hidden" },
    previewProgressRow: { position: "absolute", top: 39, left: 48, right: 48, flexDirection: "row", gap: 12 },
    previewCenter: { flex: 1, alignItems: "center", justifyContent: "center", paddingTop: 42 },
    previewWeek: { marginTop: 56, fontSize: 28, fontWeight: "900", color: "#0F6EF7", lineHeight: 36 },
    previewTitle: { marginTop: 4, fontSize: 34, fontWeight: "900", color: "#05070A", lineHeight: 42 },
    previewTimeRow: { position: "absolute", left: 30, right: 30, bottom: 29, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    previewTime: { fontSize: 24, fontWeight: "900", color: "#FFFFFF", lineHeight: 30 },
previewVideo: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" },
previewProgressTrack: { flex: 1, height: 12, borderRadius: 6, backgroundColor: "rgba(255, 255, 255, 0.55)", overflow: "hidden" },
previewProgressFill: { height: "100%", borderRadius: 6, backgroundColor: "#FFFFFF" },

    clipList: { gap: 16 },
    clipCard: { height: 128, borderWidth: 1, borderColor: "#E0E0E0", borderRadius: 14, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", paddingLeft: 14, paddingRight: 20 },
    clipThumb: { width: 96, height: 96, borderRadius: 7, backgroundColor: "#E5E5E5", marginRight: 18 },
    clipTextWrap: { flex: 1, minWidth: 0 },
    clipTitle: { fontSize: 28, fontWeight: "900", color: "#05070A", lineHeight: 36 },
    clipWeek: { marginTop: 2, fontSize: 22, fontWeight: "700", color: "#7E7E7E", lineHeight: 28 },
    clipDuration: { width: 70, textAlign: "right", fontSize: 28, fontWeight: "900", color: "#7E7E7E", lineHeight: 36 },
    clipCardDragging: { shadowColor: "#000", shadowOpacity: 0.18, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 8, transform: [{ scale: 1.02 }] },
    clipThumbImage: { width: "100%", height: "100%" },
    clipTitleInput: { height: 40, paddingVertical: 0, paddingHorizontal: 0, fontSize: 28, fontWeight: "900", color: "#05070A", lineHeight: 36, backgroundColor: "transparent" },

    titleEditModalBox: { width: "84%", paddingHorizontal: 22, paddingTop: 24, paddingBottom: 18, borderRadius: 16, backgroundColor: "#FFFFFF" },
    titleEditModalTitle: { fontSize: 18, fontWeight: "800", color: "#05070A", lineHeight: 24 },
    titleEditInput: { height: 52, marginTop: 18, paddingHorizontal: 14, borderWidth: 1, borderColor: "#E0E0E0", borderRadius: 10, backgroundColor: "#FFFFFF", fontSize: 17, fontWeight: "700", color: "#05070A" },
    titleEditButtonRow: { flexDirection: "row", gap: 10, marginTop: 18 },
    titleEditCancelButton: { flex: 1, height: 48, borderRadius: 10, backgroundColor: "#E6E6E6", alignItems: "center", justifyContent: "center" },
    titleEditCancelText: { fontSize: 15, fontWeight: "800", color: "#555555", lineHeight: 20 },
    titleEditConfirmButton: { flex: 1, height: 48, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    titleEditConfirmText: { fontSize: 15, fontWeight: "800", color: "#FFFFFF", lineHeight: 20 },

    deleteActionButton: { width: 112, height: 128, marginBottom: 14, borderRadius: 14, backgroundColor: "#FF3131", alignItems: "center", justifyContent: "center" },
    deleteActionText: { fontSize: 24, fontWeight: "900", color: "#FFFFFF", lineHeight: 30 },

    emptyText: { fontSize: 16, fontWeight: "700", color: "#808080", lineHeight: 22 },

    dragHandle: { width: 46, alignItems: "flex-end", justifyContent: "center", marginLeft: 18 },
    addClipButton: { height: 116, borderRadius: 14, backgroundColor: "#E5E5E5", alignItems: "center", justifyContent: "center", marginTop: 6 },
    addClipText: { fontSize: 26, fontWeight: "900", color: "#8A8A8A", lineHeight: 34 },
    bottomBar: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 28, backgroundColor: "rgba(244,248,255,0.94)" },
    exportButton: { height: 88, borderRadius: 12, backgroundColor: "#006BFF", alignItems: "center", justifyContent: "center" },
    exportButtonDisabled: { opacity: 0.6 },
    exportButtonText: { fontSize: 28, fontWeight: "900", color: "#FFFFFF", lineHeight: 36 },

    modalBackdrop: { flex: 1, alignItems: "center", justifyContent: "center" },
    modalDim: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: "rgba(0, 0, 0, 0.35)" },

    exportOverlay: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 50, backgroundColor: "#F4F8FF" },
    exportLoadingCenter: { flex: 1, alignItems: "center", justifyContent: "center", paddingBottom: 80 },
    exportDotRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 14, marginBottom: 50 },
    exportDotActive: { width: 12, height: 12, borderRadius: 6, backgroundColor: "#0166FF" },
    exportDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: "#BDD8FF" },
    exportLoadingText: { fontSize: 28, fontWeight: "900", color: "#05070A", lineHeight: 36 },

    exportDoneCenter: { flex: 1, alignItems: "center", justifyContent: "center", paddingBottom: 120 },
    exportMascot: { width: 180, height: 180, marginBottom: 42 },
    exportDoneTitle: { fontSize: 28, fontWeight: "900", color: "#05070A", lineHeight: 40, textAlign: "center" },
    exportDoneSubText: { marginTop: 28, fontSize: 20, fontWeight: "800", color: "#808080", lineHeight: 28, textAlign: "center" },
    exportDoneBottomBar: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 50, backgroundColor: "rgba(244,248,255,0.94)" },
    exportDoneButton: { height: 88, borderRadius: 12, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    exportDoneButtonText: { fontSize: 28, fontWeight: "900", color: "#FFFFFF", lineHeight: 36 },
});