// src/screens/login/login.styles.ts 
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#F0F6FF",
  },
  headerSpacer: { height: 50 },
  wrap: {
    flex: 1,
    maxWidth: 360,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 46,
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
  },
  logo: {
    width: 183,
    height: 35,
    marginBottom: 67,
  },
  kakaoBtn: {
    width: "100%",
    minWidth: 300,
    maxWidth: 300,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: "#FEE500",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  kakaoIco: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  kakaoText: {
    flex: 1,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
  },
  langToggle: {
    position: "absolute",
    top: 12,
    right: 12,
    height: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.12)",
    backgroundColor: "rgba(255,255,255,0.9)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  langToggleText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#111",
  },
});
