// src/screens/login/Onboarding.style.ts
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#FFFFFF" },
    keyboard: { flex: 1 },
    content: { flex: 1, paddingTop: 70, paddingHorizontal: 27 },
    title: { marginHorizontal: 5, marginBottom: 15, fontSize: 24, fontWeight: "700", lineHeight: 30, color: "#000000" },
    field: { marginTop: 20 },
    input: { width: "100%", height: 54, paddingHorizontal: 18, borderRadius: 10, borderWidth: 1, borderColor: "#E2E2E2", backgroundColor: "#FFFFFF", fontSize: 16, fontWeight: "400", color: "#000000" },
    errorText: { marginTop: 12, marginHorizontal: 5, fontSize: 14, fontWeight: "400", color: "#E53935" },
    footer: { paddingTop: 14, paddingHorizontal: 20, paddingBottom: 53, backgroundColor: "#FFFFFF", gap: 12 },
    primaryButton: { width: "100%", height: 60, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#2F80ED" },
    primaryButtonDisabled: { backgroundColor: "#E3E3E3" },
    primaryButtonText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF" },
    primaryButtonTextDisabled: { color: "#707070" },
    ghostButton: { width: "100%", height: 60, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#BDD8FF" },
    ghostButtonText: { fontSize: 16, fontWeight: "700", color: "#000000" },
    jumpLogoWrap: { marginHorizontal: 5, marginBottom: 8, alignItems: "flex-start", justifyContent: "center" },
    jumpLogo: { width: 84, height: 30 },
    dropdown: { width: "100%", minHeight: 66, paddingLeft: 22, paddingRight: 56, borderWidth: 1, borderColor: "#E2E2E2", borderRadius: 14, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    dropdownValue: { fontSize: 18, fontWeight: "500", color: "#000000" },
    dropdownPlaceholder: { color: "#9AA0A6", fontWeight: "400" },
    dropdownCaret: { width: 30, height: 30, transform: [{ rotate: "-90deg" }] },
    modalBackdrop: { flex: 1, backgroundColor: "rgba(0, 0, 0, 0.35)", justifyContent: "center", paddingHorizontal: 20 },
    modalCard: { maxHeight: "70%", borderRadius: 16, backgroundColor: "#FFFFFF", paddingTop: 20, paddingHorizontal: 16, paddingBottom: 16 },
    modalTitle: { marginBottom: 12, fontSize: 16, fontWeight: "700", color: "#111111" },
    modalList: { maxHeight: 320 },
    modalListContent: { paddingBottom: 8 },
    modalItem: { minHeight: 48, paddingHorizontal: 14, borderRadius: 10, alignItems: "flex-start", justifyContent: "center" },
    modalItemActive: { backgroundColor: "#F5F7FB" },
    modalItemText: { fontSize: 16, fontWeight: "500", color: "#5F5F5F" },
    modalItemTextActive: { color: "#000000" },
    modalCloseButton: { height: 48, marginTop: 12, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#2F80ED" },
    modalCloseButtonText: { fontSize: 15, fontWeight: "700", color: "#FFFFFF" },
});