import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#FFFFFF", paddingTop: 18, paddingHorizontal: 12, paddingBottom: 32 },
    scrollContent: { paddingBottom: 120 },
    header: {flexDirection: "row", alignItems: "center", justifyContent: "space-between", },
    headerTitle: { fontSize: 16, fontWeight: "700", color: "#000000", lineHeight: 20 },
    title: { marginTop: 39, marginHorizontal: 12, fontSize: 24, fontWeight: "700", lineHeight: 20, color: "#000000" },
    fieldGroup: { gap: 10,}, 
    field: { width: "100%", }, 
    inputWrap: { position: "relative", width: "100%", justifyContent: "center", },
    inputTimer: { paddingRight: 70, },
    timer: { position: "absolute", top: 17, right: 24, fontSize: 16, fontWeight: "500", lineHeight: 20, color: "#0166FF", },
    main: { marginHorizontal: 12, marginTop: 28,}, 
    input: { width: "100%", height: 54, paddingHorizontal: 18, borderRadius: 10, borderWidth: 1, borderColor: "#E2E2E2", backgroundColor: "#FFFFFF", fontSize: 16, fontWeight: "400", color: "#000000" },
    inputError: { borderColor: "#FF0000" },

    messageWrap: { minHeight: 20, justifyContent: "center", },
    infoText: { color: "#0166FF", fontSize: 12, fontWeight: "500", lineHeight: 20 },
    errorText: { color: "#FF0000", fontSize: 12, fontWeight: "500", lineHeight: 20 },
    messageHidden: { opacity: 0, },

    footer: { marginTop: 6, paddingHorizontal: 8, backgroundColor: "#FFFFFF" },
    primaryBtn: { width: "100%", height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    primaryBtnDisabled: { backgroundColor: "#E3E3E3" },
    primaryBtnText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF" },
    primaryBtnTextDisabled: { color: "#707070" },
    modalOverlay: { flex: 1, backgroundColor: "rgba(209, 209, 209, 0.50)", alignItems: "center", justifyContent: "center", padding: 47 },
    modalCard: { position: "relative", width: "100%", maxWidth: 600, borderRadius: 20, backgroundColor: "#FFFFFF", paddingTop: 55, paddingHorizontal: 30, paddingBottom: 45, alignItems: "center", shadowColor: "#000000", shadowOpacity: 0.25, shadowRadius: 10, shadowOffset: { width: 0, height: 0 }, elevation: 6 },
    modalCloseBtn: { position: "absolute", top: 16, right: 14 },
    modalIconWrap: { alignItems: "center", justifyContent: "center", marginBottom: 28 },
    modalIconImage: { width: 80, height: 80 },
    modalText: { marginTop: 16, marginBottom: 32, fontSize: 20, fontWeight: "500", lineHeight: 30, color: "#000000", textAlign: "center" },
    modalConfirmBtn: { width: "100%", maxWidth: 160, height: 48, borderRadius: 8, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    modalConfirmBtnText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
});