import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#FFFFFF", paddingTop: 18, paddingHorizontal: 20, paddingBottom: 32 },
    scrollContent: { paddingBottom: 120 },
    header: { position: "relative", height: 56, alignItems: "center", justifyContent: "center" },
    backBtn: { position: "absolute", left: 0, top: 8 },
    headerTitle: { fontSize: 16, fontWeight: "700", color: "#000000", lineHeight: 20 },
    title: { marginTop: 47, marginHorizontal: 12, marginBottom: 15, fontSize: 24, fontWeight: "700", lineHeight: 20, color: "#000000" },
    subtitle: { marginHorizontal: 12, marginBottom: 18, fontSize: 14, lineHeight: 20, color: "#6B6B6B" },
    field: { marginTop: 20, marginHorizontal: 12 },
    fieldSecond: { marginTop: 12 },
    input: { width: "100%", height: 54, paddingHorizontal: 18, borderRadius: 10, borderWidth: 1, borderColor: "#E2E2E2", backgroundColor: "#FFFFFF", fontSize: 16, fontWeight: "400", color: "#000000" },
    inputError: { borderColor: "#FF4D4F" },
    infoText: { marginHorizontal: 12, marginTop: 12, color: "#0166FF", fontSize: 14, fontWeight: "500", lineHeight: 20 },
    errorText: { marginHorizontal: 12, marginTop: 12, color: "#D93025", fontSize: 14, fontWeight: "500", lineHeight: 20 },
    footer: { paddingTop: 32, paddingBottom: 53, backgroundColor: "#FFFFFF" },
    primaryBtn: { width: "100%", height: 60, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    primaryBtnDisabled: { backgroundColor: "#E3E3E3" },
    primaryBtnText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF" },
    primaryBtnTextDisabled: { color: "#707070" },
    modalOverlay: { flex: 1, backgroundColor: "rgba(209, 209, 209, 0.50)", alignItems: "center", justifyContent: "center", padding: 47 },
    modalCard: { position: "relative", width: "100%", maxWidth: 600, borderRadius: 20, backgroundColor: "#FFFFFF", paddingTop: 55, paddingHorizontal: 30, paddingBottom: 45, alignItems: "center", shadowColor: "#000000", shadowOpacity: 0.25, shadowRadius: 10, shadowOffset: { width: 0, height: 0 }, elevation: 6 },
    modalCloseBtn: { position: "absolute", top: 16, right: 14 },
    modalIconWrap: { alignItems: "center", justifyContent: "center", marginBottom: 28 },
    modalIconImage: { width: 80, height: 80 },
    modalText: { marginTop: 16, marginBottom: 32, fontSize: 20, fontWeight: "500", lineHeight: 30, color: "#000000", textAlign: "center" },
    modalConfirmBtn: { width: "100%", maxWidth: 160, height: 48, borderRadius: 8, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    modalConfirmBtnText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
});