import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#FFFFFF", paddingTop: 18, paddingHorizontal: 20, paddingBottom: 32 },
    header: { position: "relative", height: 56, alignItems: "center", justifyContent: "center" },
    backBtn: { position: "absolute", left: 0, top: 8, width: 40, height: 40, alignItems: "center", justifyContent: "center" },
    headerTitle: { fontSize: 16, fontWeight: "700", lineHeight: 20, color: "#000000" },
    scrollContent: { paddingBottom: 72 },
    main: { paddingTop: 31 },
    section: { width: "100%" },
    stepTitle: { marginHorizontal: 12, marginBottom: 28, fontSize: 24, fontWeight: "700", lineHeight: 28, color: "#000000" },
    field: { marginHorizontal: 12 },
    fieldSecond: { marginTop: 18 },
    inputWrap: { position: "relative", width: "100%", justifyContent: "center" },
    input: { width: "100%", height: 54, paddingHorizontal: 23, borderWidth: 1, borderColor: "#E2E2E2", borderRadius: 10, backgroundColor: "#FFFFFF", fontSize: 16, fontWeight: "400", lineHeight: 20, color: "#000000" },
    inputError: { borderColor: "#FF0000" },
    inputTimer: { paddingRight: 70 },
    inputInline: { flex: 1, minWidth: 0 },
    timer: { position: "absolute", top: 17, right: 24, fontSize: 16, fontWeight: "500", lineHeight: 20, color: "#1569F5" },
    submitBtn: { width: "100%", height: 60, marginTop: 32, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    submitBtnDisabled: { backgroundColor: "#E3E3E3" },
    submitBtnText: { fontSize: 16, fontWeight: "400", lineHeight: 20, color: "#FFFFFF" },
    submitBtnTextDisabled: { color: "#707070" },
    infoText: { marginHorizontal: 12, marginTop: 8, color: "#0166FF", fontSize: 12, fontWeight: "500", lineHeight: 20 },
    errorText: { marginHorizontal: 12, marginTop: 8, color: "#FF0000", fontSize: 12, fontWeight: "400", lineHeight: 22 },
    labelRow: { position: "relative", flexDirection: "row", alignItems: "center", marginHorizontal: 12, marginBottom: 7 },
    label: { fontSize: 16, fontWeight: "500", lineHeight: 20, color: "#6B6B6B" },
    guideBtn: { width: 30, height: 30, marginLeft: 8, alignItems: "center", justifyContent: "center" },
    guideBubble: { position: "absolute", top: 5, left: 80, maxWidth: 180, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, backgroundColor: "#FFFFFF", shadowColor: "#000000", shadowOpacity: 0.15, shadowRadius: 10, shadowOffset: { width: 0, height: 0 }, elevation: 4, zIndex: 2 },
    guideBubbleText: { fontSize: 12, fontWeight: "400", lineHeight: 20, color: "#000000" },
    inlineField: { flexDirection: "row", alignItems: "stretch", marginHorizontal: 12, gap: 8 },
    sideBtn: { flexBasis: 93, height: 54, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    sideBtnDisabled: { backgroundColor: "#F6F6F6" },
    sideBtnConfirmed: { backgroundColor: "#ECECEC" },
    sideBtnText: { fontSize: 16, fontWeight: "500", lineHeight: 20, color: "#FFFFFF" },
    sideBtnTextDisabled: { color: "#6B6B6B" },
    sideBtnTextConfirmed: { color: "#707070" },
    passwordWrap: { position: "relative" },
    passwordInput: { paddingRight: 64 },
    passwordToggle: { position: "absolute", right: 16, top: 15, minWidth: 32, height: 24, alignItems: "center", justifyContent: "center" },
    modalOverlay: { flex: 1, backgroundColor: "rgba(209, 209, 209, 0.50)", alignItems: "center", justifyContent: "center", paddingHorizontal: 46 },
    modalCard: { width: "100%", maxWidth: 600, paddingTop: 44, paddingHorizontal: 28, paddingBottom: 34, borderRadius: 28, backgroundColor: "#FFFFFF", alignItems: "center", shadowColor: "#000000", shadowOpacity: 0.2, shadowRadius: 10, shadowOffset: { width: 0, height: 0 }, elevation: 6 },
    modalCloseBtn: { position: "absolute", top: 14, right: 12, width: 32, height: 32, alignItems: "center", justifyContent: "center" },
    modalIcon: { width: 80, height: 80, marginTop: 11, borderRadius: 40, alignItems: "center", justifyContent: "center" },
    modalIconImage: { width: 80, height: 80 },
    modalMessage: { marginTop: 4, textAlign: "center", color: "#000000", fontSize: 20, fontWeight: "400", lineHeight: 27 },
    modalConfirmBtn: { width: 160, maxWidth: "100%", height: 48, marginTop: 40, borderRadius: 10, backgroundColor: "#0166FF", alignItems: "center", justifyContent: "center" },
    modalConfirmBtnText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700", lineHeight: 24 },
});