// src/screens/student/schedule/Schedule.style.ts
import { Platform, StyleSheet } from "react-native";
import { tokens } from "../../../theme/common.Style";

export const styles = StyleSheet.create({
    screen: { flex: 1, height: "100%" as any, flexDirection: "column", overflow: "hidden", minHeight: 0, backgroundColor: tokens.colors.bg, },
    topbarMain: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 11, paddingHorizontal: 12, paddingBottom: 23, marginBottom: 9, },
    topbarNewschedule: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, marginBottom: 9, },
    topbarTitle: { fontSize: 16, fontWeight: "700", lineHeight: 20, color: tokens.colors.ink, }, 
    appTitle: { fontSize: 16, fontWeight: "700", lineHeight: 20, color: tokens.colors.ink, }, 
    iconBtn: { width: 24, height: 24, alignItems: "center", justifyContent: "center", backgroundColor: "transparent", }, 

    monthRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10, },
    monthLeft: { flexDirection: "row", alignItems: "center", gap: 4 as any, },
    monthLeftH1: { fontSize: 24, fontWeight: "700", color: tokens.colors.ink, lineHeight: 50, },
    monthBtn: { width: 44, height: 44, backgroundColor: "transparent", borderWidth: 0, padding: 0, alignItems: "center", justifyContent: "center", }, 
    monthPop: { position: "absolute", zIndex: 1000, backgroundColor: "#fff", borderWidth: 1, borderColor: "#eee", borderRadius: 12, padding: 10, minWidth: 120, ...(tokens.shadow.card as any), },
    monthMenu: { flexDirection: "column", maxHeight: 200, }, 
    monthItem: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 6, },
    monthItemText: { fontSize: 16, color: tokens.colors.ink, },
    monthItemCurrentText: { color: tokens.colors.primary, fontWeight: "700", }, 

    card: { backgroundColor: "#fff", borderRadius: 10, padding: 16, marginBottom: 11, borderWidth: 2, borderColor: "transparent", ...(tokens.shadow.card as any), },
    cardSelected: { borderColor: tokens.colors.primary, },
    cardLocked: { borderWidth: 0, ...(Platform.OS === "android" ? { elevation: 0 } : {}), },
    item: { flexDirection: "row", alignItems: "center", gap: 25 as any, },
    thumb: { width: 28, height: 28, marginLeft: 8, borderRadius: 5, backgroundColor: "#E3E3E3", flexShrink: 0, }, 
    thumbSelected: { backgroundColor: tokens.colors.primary, },
    title: { fontSize: 16, fontWeight: "700", color: tokens.colors.ink, marginBottom: 5, },
    subtitle: { minHeight: 16, fontSize: 14, color: "#888", fontWeight: "500", },

    newEvent: { flexGrow: 1, minHeight: 0, paddingRight: 36, paddingBottom: 240, paddingLeft: 36, }, 
    titleInput: { width: "100%", height: 48, borderWidth: 0, backgroundColor: "#fff", borderRadius: 10, paddingTop: 12, paddingBottom: 12, paddingHorizontal: 21, fontSize: 20, lineHeight: 24, color: tokens.colors.ink, marginTop: 13, marginBottom: 21, fontWeight: "600", },
    row: { height: 44, flexDirection: "row", alignItems: "center", gap: 16 as any, padding: 0, }, 
    rowCol: { flex: 1, alignSelf: "stretch", flexDirection: "column", justifyContent: "flex-end", },
    rowHead: { flexDirection: "row", alignItems: "center", gap: 15 as any, },
    rowToday: { fontSize: 16, marginBottom: 2, fontWeight: "700", lineHeight: 20, color: tokens.colors.ink, },
    rowSub: { paddingLeft: 39, fontSize: 14, color: tokens.colors.muted, fontWeight: "500", lineHeight: 20, }, 
    rowSubBtn: { paddingLeft: 39, paddingRight: 39, },

    addBtnWrapper: { marginLeft: "auto", position: "relative", width: 24, alignItems: "flex-start", marginTop: -20, }, 
    addDate: { position: "absolute", left: 0, width: 24, height: 24, backgroundColor: "transparent", borderRadius: 8, alignItems: "center", justifyContent: "center", }, 
    add: { position: "absolute", left: 0, width: 24, height: 24, backgroundColor: "transparent", borderRadius: 8, alignItems: "center", justifyContent: "center", },

    scheduleCardDatetime: { backgroundColor: "#fff", borderRadius: 10, paddingVertical: 16, paddingHorizontal: 21, },
    scheduleLineDate: { flexDirection: "row", alignItems: "center", gap: 18 as any, },
    scheduleLineTime: { flexDirection: "row", alignItems: "center", gap: 18 as any, marginTop: 19, },
    scheduleLineTimePills: { flexDirection: "row", alignItems: "center", gap: 16 as any, marginTop: 19, },
    scheduleLineIcon: { width: 24, height: 24, },
    scheduleLineIconTime: { width: 24, height: 24, },

    dateInline: { flex: 1, flexDirection: "row", alignItems: "center", gap: 21 as any, },
    datePill: { flex: 1, minWidth: 96, height: 36, backgroundColor: "#F1F1F1", borderRadius: 18, paddingVertical: 8, paddingHorizontal: 16, alignItems: "center", justifyContent: "center", },
    datePillText: { fontSize: 16, fontWeight: "600", lineHeight: 20, color: "#808080", },
    dateSep: { fontSize: 16, lineHeight: 20, color: "#808080", fontWeight: "600", },

    rowToggleLeft: { flex: 1, flexDirection: "row", alignItems: "center", gap: 12 as any, }, 
    rowToggleLeftText: { fontSize: 16, fontWeight: "600", color: tokens.colors.ink, },
    switch: { width: 48, height: 28, borderRadius: 25, backgroundColor: "#F1F1F1", position: "relative", marginLeft: "auto", justifyContent: "center", paddingHorizontal: 2, }, 
    switchOn: { backgroundColor: tokens.colors.primary, },
    switchThumb: { width: 24, height: 24, borderRadius: 999, backgroundColor: "#fff", transform: [{ translateX: 0 }], }, 
    switchThumbOn: { transform: [{ translateX: 20 }], },

    rowIconEmpty: { width: 24, },
    timeInline: { flex: 1, flexDirection: "row", alignItems: "center", gap: 21 as any, },
    timePill: { flex: 1, minWidth: 96, height: 36, backgroundColor: "#F1F1F1", borderRadius: 18, paddingVertical: 8, paddingHorizontal: 10, alignItems: "center", justifyContent: "center", },
    timePillText: { fontSize: 16, fontWeight: "600", lineHeight: 20, color: "#808080", },

    memoBox: { marginTop: 20, height: 120, backgroundColor: "#fff", borderRadius: 12, paddingVertical: 14, paddingHorizontal: 29, },
    memoInput: { width: "100%", minHeight: 90, fontSize: 14, lineHeight: 14, color: "#000", fontWeight: "600", textAlignVertical: "top", },

    footerFixed: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 20, paddingBottom: 53, backgroundColor: "transparent", }, 
    btnPrimary: { width: "100%", height: 60, borderRadius: tokens.radius.r10, backgroundColor: tokens.colors.primary, alignItems: "center", justifyContent: "center", }, 
    btnPrimaryText: { color: "#fff", fontSize: 16, fontWeight: "500", lineHeight: 50, },
    btnDisabled: { backgroundColor: "#F1F1F1", color: "#A2A2A2",},
    btnDanger: { backgroundColor: tokens.colors.danger, },
    btnDelete: { width: "100%", height: 60, paddingHorizontal: 16, paddingVertical: 16, borderRadius: 10, backgroundColor: "#BDD8FF", marginBottom: 12, justifyContent: "center", alignItems: "center", },
    btnDeleteText: { fontSize: 16, fontWeight: "500", color: tokens.colors.ink, },
    
    sheetBackdrop: { ...StyleSheet.absoluteFill, backgroundColor: "transparent", justifyContent: "flex-end", }, 
    
    sheetCard: { zIndex: 1011, position: "absolute", right: 44, top: 231, width: 150, maxHeight: 180, backgroundColor: "#fff", borderRadius: 12, paddingTop: 10, paddingRight: 5, paddingBottom: 10, paddingLeft: 14, overflow: "hidden", ...(tokens.shadow.card as any), }, 
    sheetHeader: { display: "none", }, 
    sheetTitle: { fontSize: 16, fontWeight: "600", color: tokens.colors.ink, },
    sheetCloseBtn: { width: 24, height: 24, },
    sheetCols: { display: "flex", },
    sheetCol: { padding: 0, overflow: "hidden", },
    sheetOverlay: { flex: 1, justifyContent: "flex-end", },
    timeList: { maxHeight: 150, },
    timeItem: { width: "100%", paddingVertical: 2, paddingHorizontal: 4, },
    timeItemText: { fontSize: 14, lineHeight: 20, color: "#AEAEAE", fontWeight: "500", }, 
    timeItemDisabled: { opacity: 0.35, },
    timeItemSelected: { borderRadius: 5, backgroundColor: tokens.colors.primary, },
    timeItemSelectedText: { color: "#fff", },  
    sheetCardDate: { position: "absolute", left: 0, right: 0, bottom: 0, width: "100%", maxWidth: "100%", backgroundColor: "#fff", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden", }, 
    sheetCardDate5w: { height: "auto" as any, },
    sheetCardDate6w: { height: "auto" as any, maxHeight: 790, },
    dateRangeBody: { paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0, },
    
    cal: { position: "relative", },
    calHeader: { flexDirection: "column", gap: 28 as any, marginBottom: 10, paddingTop: 22, paddingHorizontal: 14, paddingBottom: 10, },
    calHeaderTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", },
    calHeaderBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingLeft: 44, paddingRight: 40, }, 
    calCloseBtn: { borderRadius: 10, paddingTop: 10, paddingRight: 2, width: 40, height: 40, alignItems: "center", justifyContent: "center", backgroundColor: "transparent", },
    calTitle: { fontSize: 16, fontWeight: "700", color: tokens.colors.ink, },
    calNav: { flexDirection: "row", gap: 12 as any, },
    calNavBtn: { width: 24, height: 24, alignItems: "center", justifyContent: "center", backgroundColor: "transparent", },
    calBody: { paddingRight: 52, paddingLeft: 48, paddingBottom: 0, },
    calWeek: { flexDirection: "row", justifyContent: "space-between", marginBottom: 17, paddingHorizontal: 5, }, 
    calWeekday: { width: 35, textAlign: "center", paddingVertical: 6, fontSize: 16, fontWeight: "500", color: "#333333", }, 
    calGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 6 as any, columnGap: 0 as any, }, 
    calCell: { position: "relative", width: "14.2857%" as any, height: 35, alignItems: "center", justifyContent: "center", },
    calCellEmpty: { opacity: 0, }, 
    calCellInRange: {},
    calCellStart: {},
    calCellEnd: {},
    calDay: { position: "relative", zIndex: 1, width: 35, height: 35, borderRadius: 6, alignItems: "center", justifyContent: "center", backgroundColor: "transparent", }, 
    calDayText: { fontSize: 16, fontWeight: "500", color: "#666666", },
    calDaySelected: { backgroundColor: tokens.colors.primary, },
    calDaySelectedText: { color: "#fff", },
    calRange: { position: "absolute", top: 3, bottom: 3, left: 0, right: 0, backgroundColor: "rgba(1, 102, 255, 0.20)", zIndex: 0, },
    calRangeStart: { left: "50%", right: -StyleSheet.hairlineWidth * 0.3, },
    calRangeEnd: { left: 0, right: "50%", },
    calRangeSingle: { left: "50%", right: "50%", opacity: 0, },
    
    calDayFront: { zIndex: 1, }, 
    calRangeHint: { marginTop: 10, fontSize: 14, opacity: 0.55, textAlign: "center", }, 

    sheetConfirm: { width: "auto", marginTop: 60, marginHorizontal: 20, marginBottom: 53, height: 60, borderRadius: tokens.radius.r10, backgroundColor: tokens.colors.primary, alignItems: "center", justifyContent: "center", },
    sheetConfirmText: { color: "#fff", fontSize: 16, fontWeight: "700", },
    
    timewheel: { paddingTop: 15, paddingHorizontal: 18, paddingBottom: 12, },
    timewheelPeriod: { textAlign: "center", fontSize: 14, fontWeight: "500", marginBottom: 10, color: tokens.colors.muted, }, 
    timewheelRow: { flexDirection: "row", gap: 5 as any, paddingHorizontal: 12, paddingBottom: 6, }, 
    timewheelItem: { minWidth: 73, width: 73, height: 73, alignItems: "center", justifyContent: "center", borderRadius: 9, backgroundColor: "transparent", }, 
    timewheelItemText: { fontSize: 16, fontWeight: "700", color: tokens.colors.ink, }, 
    timewheelItemSelected: { backgroundColor: tokens.colors.primary, },
    timewheelItemSelectedText: { color: "#fff", },
    timewheelItemLeftEdgeText: { opacity: 0.5, },

    detailTopbar: { height: 50, paddingTop: 20, paddingRight: 12, paddingBottom: 20, paddingLeft: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between",  backgroundColor: tokens.colors.bg, },
    detailTopbarTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "700", lineHeight: 20, color: tokens.colors.ink, }, 
    detailTopbarClose: { width: 44, height: 44, alignItems: "center", justifyContent: "center", backgroundColor: "transparent", }, 

    detailBody: { paddingTop: 17, paddingBottom: 24, },
    detailSingleWrap: { paddingHorizontal: 20, }, 
    detailPage: { justifyContent: "center", alignItems: "center", paddingTop: 4,},
    detailScrollView: { paddingBottom: 10,},

    detailCard: { width: "100%", minHeight: 450, backgroundColor: "#fff", borderRadius: 10, ...(tokens.shadow.card as any), }, 
    qaWrap: { minHeight: 450, flexDirection: "column", gap: 21 as any,  paddingTop: 30,paddingRight: 18, paddingBottom: 17, paddingLeft: 22, }, 
    qaQText: { fontSize: 16, fontWeight: "700", color: tokens.colors.ink, },
    qaAText: { fontSize: 16, fontWeight: "500", color: tokens.colors.ink, lineHeight: 24, },

    detailCenter: { minHeight: 450, alignItems: "center", justifyContent: "center", }, 
    detailEmpty: { fontSize: 12, fontWeight: "500", color: "#979797", },
    muted: { color: "#7a7a7a", },

    detailDots: { flexDirection: "row", justifyContent: "center", minHeight: 10, marginBottom: 30, gap: 12 as any, },
    detailDotsPlaceholder: { opacity: 0, },
    dot: { width: 10, height: 10, borderRadius: 9999, backgroundColor: "#D9D9D9", },
    dotActive: { backgroundColor: tokens.colors.primary, }, 
    detailFooter: { marginTop: "auto", },
    detailRecordedAt: { fontSize: 12, fontWeight: "500", color: "#979797", },
});