import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: "#F0F6FF" },
    topbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 40, paddingRight: 20, paddingBottom: 23, paddingLeft: 20, height: 113, backgroundColor: "#F0F6FF" },
    iconButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
    appTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "700", color: "#000000" },
    topActions: { flexDirection: "row", alignItems: "center", gap: 20 },
    main: { flex: 1, paddingTop: 27, paddingRight: 20, paddingBottom: 30, paddingLeft: 20 },
    titleSection: { marginBottom: 24, paddingHorizontal: 4 },
    todayText: { marginLeft: 3, color: "#808080", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    activityTitle: { marginTop: 11, color: "#000000", fontSize: 24, fontWeight: "700", lineHeight: 28 },
    progressCard: { minHeight: 160, paddingTop: 18, paddingRight: 16, paddingBottom: 22, paddingLeft: 16, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", justifyContent: "space-between", marginBottom: 10 },
    progressLabel: { marginLeft: 4, color: "#6B6B6B", fontSize: 14, fontWeight: "700" },
    progressValue: { marginLeft: 7, color: "#000000", fontSize: 36, fontWeight: "700", lineHeight: 40 },
    progressTrack: { width: "100%", height: 8, borderRadius: 7, backgroundColor: "#BDD8FF", overflow: "hidden" },
    progressFill: { height: "100%", borderRadius: 7, backgroundColor: "#0166FF" },
    metricCard: { width: "100%", minHeight: 84, marginBottom: 10, paddingTop: 15, paddingRight: 12, paddingBottom: 20, paddingLeft: 12, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 10, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center" },
    metricTextWrap: { flex: 1, minWidth: 0, marginLeft: 8, gap: 7 },
    metricLabel: { color: "#6B6B6B", fontSize: 14, fontWeight: "700", lineHeight: 20 },
    metricValue: { color: "#000000", fontSize: 24, fontWeight: "700", lineHeight: 28 },
    metricBadge: { minWidth: 84, height: 36, paddingHorizontal: 10, borderRadius: 18, backgroundColor: "#BDD8FF", alignItems: "center", justifyContent: "center" },
    metricBadgePrimary: { backgroundColor: "#0166FF" },
    metricBadgeText: { color: "#0166FF", fontSize: 16, fontWeight: "700" },
    metricBadgeTextPrimary: { color: "#FFFFFF" },
    metricArrow: { width: 36, height: 36, marginLeft: 2, alignItems: "center", justifyContent: "center" },
    scheduleSection: { marginTop: 47 },
    scheduleTitle: { marginHorizontal: 11, marginBottom: 21, color: "#000000", fontSize: 20, fontWeight: "700", lineHeight: 24 },
    scheduleList: { gap: 10 },
    scheduleItem: { width: "100%", minHeight: 84, paddingVertical: 18, paddingHorizontal: 20, borderWidth: 1, borderColor: "#E6E6E6", borderRadius: 14, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 14 },
    scheduleIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: "#E7E7E7", alignItems: "center", justifyContent: "center" },
    scheduleIconCompleted: { backgroundColor: "#BDD8FF" },
    scheduleTextWrap: { flex: 1, minWidth: 0, gap: 5 },
    scheduleItemTitle: { color: "#000000", fontSize: 16, fontWeight: "700", lineHeight: 20 },
    scheduleItemDate: { color: "rgba(0, 0, 0, 0.50)", fontSize: 14, fontWeight: "500", lineHeight: 20 },
    empty: { minHeight: 120, color: "#808080", fontSize: 15, fontWeight: "700", textAlign: "center", textAlignVertical: "center" },
    emptyWrap: { minHeight: 120, alignItems: "center", justifyContent: "center" },
});